# # This file should contain all the record creation needed to seed the database with its default values.
# # The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
# #
# # Examples:
# #
# #   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
# #   Character.create(name: 'Luke', movie: movies.first)
#
# City.create([
#   {name: "Hà Nội"},
#   {name: "Đà Nẵng"},
#   {name: "Hồ Chí Minh"}
#   ])
#
# District.create([
#   {city_id: "1", name: "Ba Đình"},
#   {city_id: "1", name: "Bắc Từ Liêm"},
#   {city_id: "1", name: "Cầu Giấy"},
#   {city_id: "1", name: "Đống Đa"},
#   {city_id: "1", name: "Hai Bà Trưng"},
#   {city_id: "1", name: "Hoàn Kiếm"},
#   {city_id: "1", name: "Hoàng Mai"},
#   {city_id: "1", name: "Long Biên"},
#   {city_id: "1", name: "Nam Từ Liêm"},
#   {city_id: "1", name: "Thanh Xuân"},
#   {city_id: "1", name: "Tây Hồ"},
#   {city_id: "1", name: "Ba Vì"},
#   {city_id: "1", name: "Chương Mỹ,"},
#   {city_id: "1", name: "Đan Phượng"},
#   {city_id: "1", name: "Đông Anh"},
#   {city_id: "1", name: "Gia Lâm"},
#   {city_id: "1", name: "Hoài Đức"},
#   {city_id: "1", name: "Mê Linh"},
#   {city_id: "1", name: "Mỹ Đức"},
#   {city_id: "1", name: "Phúc Thọ"},
#   {city_id: "1", name: "Phú Xuyên"},
#   {city_id: "1", name: "Quốc Oai"},
#   {city_id: "1", name: "Sóc Sơn"},
#   {city_id: "1", name: "Thạch Thất"},
#   {city_id: "1", name: "Thanh Oai"},
#   {city_id: "1", name: "Thanh Trì"},
#   {city_id: "1", name: "Thường Tín"},
#   {city_id: "1", name: "Ứng Hòa"},
#   {city_id: "2", name: "Hoàng Sa "},
#   {city_id: "2", name: "Ngũ Hành Sơn "},
#   {city_id: "2", name: "Sơn Trà "},
#   {city_id: "2", name: "Hòa Vang "},
#   {city_id: "2", name: "Thanh Khê "},
#   {city_id: "2", name: "Cẩm Lệ "},
#   {city_id: "2", name: "Hải Châu "},
#   {city_id: "2", name: "Liên Chiểu"},
#   {city_id: "3", name: "Quận 1"},
#   {city_id: "3", name: "Quận 2"},
#   {city_id: "3", name: "Quận 3"},
#   {city_id: "3", name: "Quận 4"},
#   {city_id: "3", name: "Quận 5"},
#   {city_id: "3", name: "Quận 6"},
#   {city_id: "3", name: "Quận 7"},
#   {city_id: "3", name: "Quận 8"},
#   {city_id: "3", name: "Quận 9"},
#   {city_id: "3", name: "Quận 10"},
#   {city_id: "3", name: "Quận 11"},
#   {city_id: "3", name: "Quận 12"},
#   {city_id: "3", name: "Thủ Đức"},
#   {city_id: "3", name: "Gò Vấp"},
#   {city_id: "3", name: "Bình Thạnh"},
#   {city_id: "3", name: "Tân Bình"},
#   {city_id: "3", name: "Tân Phú"},
#   {city_id: "3", name: "Phú Nhuận"},
#   {city_id: "3", name: "Bình Tân"},
#   {city_id: "3", name: "Củ Chi"},
#   {city_id: "3", name: "Hóc Môn"},
#   {city_id: "3", name: "Bình Chánh"},
#   {city_id: "3", name: "Nhà Bè"},
#   {city_id: "3", name: "Cần Giờ"},
#
# ])
#
# User.create([
#   {name: "admin", email: "admin@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0989899466" , birthday: "1993-10-23", gender: "1", role: "5"},
#   {name: "le khoa", email: "lekhoa@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0989899466" , birthday: "1993-10-23", gender: "1", role: "0", avatar_file_name: "khoa1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "99339", avatar_updated_at: "2017-05-06 04:09:40"  },
#   {name: "Thanh Minh", email: "nguyenminh@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "01672278791" , birthday: "1994-10-10", gender: "1", role: "0", avatar_file_name: "minh.jpg" , avatar_content_type: "image/jpeg", avatar_file_size: "13297", avatar_updated_at: "2017-05-06 04:09:40"  },
#   {name: "Hữu Nhựt", email: "nguyennhut@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0964823281" , birthday: "1994-1-10", gender: "1", role: "0" , avatar_file_name: "nhut.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "7242", avatar_updated_at: "2017-05-06 04:09:40"  },
#   {name: "Hoàng Phúc", email: "nguyenphuc@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "01687786165" , birthday: "1994-4-1", gender: "1", role: "0" ,avatar_file_name: "phuc1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "41368", avatar_updated_at: "2017-05-06 04:09:40"  },
#   {name: "Viết Huy", email: "nguyenhuy@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "01263130140" , birthday: "1994-12-12", gender: "1", role: "0", avatar_file_name: "huy.jpg" , avatar_content_type: "image/jpeg", avatar_file_size: "111809" , avatar_updated_at: "2017-05-06 04:09:40" },
#   {name: "Chu Tuấn", email: "chutuan@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0975270998" , birthday: "1993-6-2", gender: "1", role: "0", avatar_file_name: "tuan.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "19625", avatar_updated_at: "2017-05-06 04:09:40" },
#   {name: "Lê Huyen", email: "lehuyen@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0984234152" , birthday: "1986-12-21", gender: "1", role: "0", avatar_file_name: "huyen1.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "64149", avatar_updated_at: "2017-05-06 04:09:40"  },
#   {name: "Lê Dũng", email: "ledung@gmail.com", password: "123456",district_id: "36", address: "ktx", phone: "0975152452" , birthday: "1984-12-21", gender: "1", role: "0", avatar_file_name: "dung.jpg", avatar_content_type: "image/jpeg", avatar_file_size: "113957", avatar_updated_at: "2017-05-06 04:09:40"  }
# ])
#
# Restaurant.create([
#   {user_id: "2", district_id: "31",name:"GoGi House", address: "910A Ngô Quyền", phone: "1900 6622", actived: "0"  },
#   {user_id: "2", district_id: "31",name:"GoGi House", address: "910A Ngô Quyền", phone: "1900 6622", actived: "1", image_file_name: "nhahanh7.jpg", image_content_type: "image/jpeg" , image_file_size: "1630816" },
#   {user_id: "2", district_id: "35",name:"Pizza Hut", address: "319 Lê Duẩn", phone: "19001822", actived: "0"  },
#   {user_id: "2", district_id: "35",name:"Pizza Hut", address: "319 Lê Duẩn", phone: "19001822", actived: "1" , image_file_name: "nha-hang-quan-bar-an-tuong.jpg", image_content_type: "image/jpeg" , image_file_size: "89877" },
#   {user_id: "2", district_id: "33",name:"Han Cook Cafe & Food", address: "318 Hải Phòng", phone: "1900 6622", actived: "0"  },
#   {user_id: "2", district_id: "33",name:"Han Cook Cafe & Foode", address: "318 Hải Phòng", phone: "1900 6622", actived: "1", image_file_name: "nam_hoa_vien.JPG", image_content_type: "image/jpeg" , image_file_size: "249471"  },
#
#   {user_id: "4", district_id: "35",name:"Bánh Tráng Thịt Heo Trần", address: "4 Lê Duẩn", phone: "1900 6622", actived: "0"  },
#   {user_id: "4", district_id: "35",name:"Bánh Tráng Thịt Heo Trần", address: "4 Lê Duẩn", phone: "1900 6622", actived: "1" , image_file_name: "anh1_c.jpg", image_content_type: "image/jpeg" , image_file_size: "72964" },
#   {user_id: "4", district_id: "35",name:"Xiên Que", address: "138 Nguyễn Thị Minh Khai", phone: "1900 6622", actived: "0"  },
#   {user_id: "4", district_id: "35",name:"Xiên Que", address: "138 Nguyễn Thị Minh Khai", phone: "1900 6622", actived: "1" , image_file_name: "nhahang5.jpg", image_content_type: "image/jpeg" , image_file_size: "385458"  },
#   {user_id: "4", district_id: "35",name:"The Salmon Restaurant", address: "57 Hoàng Văn Thụ", phone: "1900 6622", actived: "0"  },
#   {user_id: "4", district_id: "35",name:"The Salmon Restaurant", address: "57 Hoàng Văn Thụ", phone: "1900 6622", actived: "1" , image_file_name: "nhahang11.jpg", image_content_type: "image/jpeg" , image_file_size: "69085"   },
#
#   {user_id: "5", district_id: "35",name:"Al Fresco's", address: "178 Trần Phú", phone: "1900 6622", actived: "0"  },
#   {user_id: "5", district_id: "35",name:"Al Fresco's", address: "178 Trần Phú", phone: "1900 6622", actived: "1"  , image_file_name: "nhahang9.jpg", image_content_type: "image/jpeg" , image_file_size: "80675"  },
#   {user_id: "5", district_id: "35",name:"Dasushi", address: "150 Phan Chu Trinh", phone: "1900 6622", actived: "0"  },
#   {user_id: "5", district_id: "35",name:"Dasushi", address: "150 Phan Chu Trinh", phone: "1900 6622", actived: "1", image_file_name: "nhahang7.jpg", image_content_type: "image/jpeg" , image_file_size: "1045128"   },
#   {user_id: "5", district_id: "35",name:"PapaSteak - Beefsteak", address: "83 Thái Phiên", phone: "1900 6622", actived: "0"  },
#   {user_id: "5", district_id: "35",name:"PapaSteak - Beefsteak", address: "83 Thái Phiên", phone: "1900 6622", actived: "1", image_file_name: "nahhang8.jpg", image_content_type: "image/jpeg" , image_file_size: "81719"     },
#
#   {user_id: "6", district_id: "33",name:"SaSin - Mì Cay 7 Cấp Độ Hàn Quốc", address: "315 Nguyễn Văn Linh", phone: "1900 6622", actived: "0"  },
#   {user_id: "6", district_id: "33",name:"SaSin - Mì Cay 7 Cấp Độ Hàn Quốc", address: "315 Nguyễn Văn Linh", phone: "1900 6622", actived: "1"  },
#   {user_id: "6", district_id: "33",name:"Điểm Tâm 294", address: "294 Nguyễn Hoàng", phone: "1900 6622", actived: "0"  },
#   {user_id: "6", district_id: "33",name:"Điểm Tâm 294", address: "294 Nguyễn Hoàng", phone: "1900 6622", actived: "1" },
#   {user_id: "6", district_id: "36",name:"Sông Hương - Đặc Sản Huế", address: "137 Trần Nguyên Đán", phone: "1900 6622", actived: "0"  },
#   {user_id: "6", district_id: "36",name:"Sông Hương - Đặc Sản Huế", address: "137 Trần Nguyên Đán", phone: "1900 6622", actived: "1" },
#
#   {user_id: "7", district_id: "36",name:"Quán Vân - Bánh Bèo - Nậm & Bột Lọc", address: "13A Thanh Tịnh", phone: "1900 6622", actived: "0"  },
#   {user_id: "7", district_id: "36",name:"Quán Vân - Bánh Bèo - Nậm & Bột Lọc", address: "13A Thanh Tịnh", phone: "1900 6622", actived: "1"  },
#   {user_id: "7", district_id: "31",name:"Hải Sản Năm Đảnh", address: "K139/H59/38 Trần Quang Khải, P. Thọ Quang", phone: "1900 6622", actived: "0"  },
#   {user_id: "7", district_id: "31",name:"Hải Sản Năm Đảnh", address: "K139/H59/38 Trần Quang Khải, P. Thọ Quang", phone: "1900 6622", actived: "1"  },
#   {user_id: "7", district_id: "31",name:"Hải Sản Bé Mặn A", address: "Lô 11 Võ Nguyên Giáp", phone: "1900 6622", actived: "0"  },
#   {user_id: "7", district_id: "31",name:"Hải Sản Bé Mặn A", address: "Lô 11 Võ Nguyên Giáp", phone: "1900 6622", actived: "1"},
#
#   {user_id: "8", district_id: "6",name:"Lẩu Cua Khôi", address: "79 Trần Hưng Đạo", phone: "1900 6622", actived: "1"  , image_file_name: "nahhang8.jpg", image_content_type: "image/jpeg" , image_file_size: "80753"   },
#   {user_id: "8", district_id: "3",name:"Chả Cá Hà Thành", address: "20 Nguyễn Văn Huyên Kéo Dài", phone: "1900 6622", actived: "1", image_file_name: "nhahang3.jpg", image_content_type: "image/jpeg" , image_file_size: "583492"     },
#   {user_id: "8", district_id: "5",name:"BlackBall - Chè & Trà Sữa Đài Loan", address: "32 Quang Trung", phone: "1900 6622", actived: "1", image_file_name: "nahhang8.jpg", image_content_type: "image/jpeg" , image_file_size: "81719"  },
#   {user_id: "8", district_id: "5",name:"Hiệu Lực - Bánh Mì Chảo", address: "326 Bà Triệu", phone: "1900 6622", actived: "1" },
#   {user_id: "8", district_id: "1",name:"Miwa - Ẩm thực Nhật", address: "31 Láng Hạ", phone: "1900 6622", actived: "1"  },
#   {user_id: "8", district_id: "3",name:"Vua Trộn Hà Nội - Các Món Trộn", address: "Ki Ốt 6 Dương Khuê", phone: "1900 6622", actived: "1" },
#   {user_id: "8", district_id: "4",name:"Quẩy Nóng, Bánh Gối ", address: "149 Nguyễn Lương Bằng", phone: "1900 6622", actived: "1"  },
#   {user_id: "8", district_id: "5",name:"Bánh Tráng Trộn Cô Toàn", address: "A17 Tạ Quang Bửu", phone: "1900 6622", actived: "1"  },
#   {user_id: "8", district_id: "1",name:"Lẩu Đức Trọc", address: "69 Phó Đức Chính", phone: "1900 6622", actived: "1"  },
#
#   {user_id: "3", district_id: "39",name:"Vỹ Dạ Quán ", address: "146 Võ Văn Tần", phone: "1900 6622", actived: "1" , image_file_name: "nhahang4.jpg", image_content_type: "image/jpeg" , image_file_size: "259582"   },
#   {user_id: "3", district_id: "46",name:"Ngọc Bích - Cơm Gà Nướng", address: "14 Đồng Nai", phone: "1900 6622", actived: "1" , image_file_name: "nhahang3.jpg", image_content_type: "image/jpeg" , image_file_size: "583492"   },
#   {user_id: "3", district_id: "37",name:"Lẩu Bò Như Ý ", address: "19D Cống Quỳnh", phone: "1900 6622", actived: "1", image_file_name: "nhahang1.jpg", image_content_type: "image/jpeg" , image_file_size: "484752"    },
#   {user_id: "3", district_id: "37",name:"Lẩu Bò Quang Khải", address: "60 Hồ Hảo Hớn ", phone: "1900 6622", actived: "1", image_file_name: "nhahang2.jpg", image_content_type: "image/jpeg" , image_file_size: "185523"     },
#   {user_id: "3", district_id: "50",name:"Sài Gòn Nướng", address: "372 Dương Quảng Hàm", phone: "1900 6622", actived: "1" },
#   {user_id: "3", district_id: "41",name:"Quán Cô Út - Bò Né", address: "008 Lê Hồng Phong", phone: "1900 6622", actived: "1"   },
#   {user_id: "3", district_id: "37",name:"Buzza Pizza", address: "9 Nguyễn Trung Trực", phone: "1900 6622", actived: "1"  }
#   ])
#
# Post.create([
#   {user_id: "3", title: "Cảm thấy tuyệt vời cùng cửa hàng Bánh Năm", content: "Chiều thứ 7 ngày 23/5 tới, cửa hàng Bánh Năm đã khai trương địa điểm đầu tiên tại 151A Xô Viết Nghệ Tĩnh, phường 17, quận Bình Thạnh, Tp HCM. Mọi người ghé ủng hộ nhé  "},
#   {user_id: "2", title: "Cảm thấy ngon tại Quán bánh xèo Bà Dưỡng", content: "Thường ăn bánh xèo giá tầm 5k-10k, lần đầu nghe cái bánh xèo 20k thấy cũng là lạ, đến ăn xem nó thế nào. Đi 2 người, kêu 4 cái, đem ra dĩa 4 cái, thấy bánh nho nhỏ, nghĩ bụng 1 người ăn chắc cũng chưa no lắm. Nghĩ bụng là thế, 2 người ăn xong 3 cái là no.  Nước chấm 2 loại đều đậm đà. Bánh xèo chờ hơi lâu 1 chút. Có món bánh tráng thịt heo nghe nói cũng được, lần sau sẽ thử xem thế nào"},
#   {user_id: "7", title: "Rất ngon nhé - Nhật Vy - Phở Hà Nội", content: "Phở đậm chất Hà Nội. Thịt tái mềm, gầu ngon, nước trong vắt. Đang khuyến mãi nên tô to trà bá có 20k no nê. Lâu rồi mới ăn tô phở đúng vị. Quán rộng rãi, thoáng mát. Sẽ ghé nhiều lần."},
#   {user_id: "4", title: "Bún Đậu Cô Nhỏ thiên đường của mắm", content: "Minh đã đến đây nhiều lần giờ mới viết =)) Không gian thoáng mát, chỗ khá dễ tìm  Đồ ăn ngon, nước ép khá được , cơ mà hôm bữa đến ăn nó chua quá à  Giá thì đắt hơn quán khác 1 tí, phục vụ đồ ăn nhanh  Sẽ quay lại "},
#   {user_id: "5", title: " BlackBall - 32 Quang Trung, Hải Châu, Đà Nẵng", content: "Những món ăn cay là một phần không thể thiếu trong văn hóa ẩm thực Việt Nam, đem đến cho thực khách những trải nghiệm mới mẻ và khó quên.Hãy đến với cửa hàng BlackBall của chúng tôi, địa chỉ: 32 Quang Trung, Hải Châu, Đà Nẵng "},
#   {user_id: "2", title: "Ngon mà rẻ tại Ba Lép - Nhậu Bình Dân", content: "công nhận là ngon món hầu điéu với cua j đó đặc sản Nha Trang có 60k ngon bổ rẻ . ma sò điệp nướng mở hành thấy ai ăn cũng đầy đủ sao mình ăn thấy trớt quớt ko thay hành mở j hêt ( chăc tại keu sò nướng thôi) them món mực nua ma ham ăn ko chup . tong thiet hại 3 món 170k . nhắc lại cung còn thèm . ma gần nhà nua chứ đi có 5 phut la tới rồi quá thuận tiện . muốn an nhím biển thử mà hết rồi anh nhân viên kêu muon an đầy đủ phai di 4h chiều"},
#   {user_id: "7", title: "Cũng thưởng thức hải sải tại Quốc Huy 68 ", content: "Nhà hành này vừa mới khai trương luôn, nằm ngay con đường khá là đông khách sạn ngay sát biển luôn í. Mình tới đây cùng với bạn đi hai người thôi nên chỉ gọi lẩu và tôm tít xóc tỏi. Tôm tít phải nói là siêu to luôn nha, rất lf đáng đồng tiền bát gạo luôn ấy. Lẩu nhiều dễ sợ, tôm, mực, cá đều tươi rói hết. Nồi lẩu này phải 4 người ăn mới hết chứ 2 đứa mình ăn le lưỡi luôn."},
#   {user_id: "5", title: "Liferia Coffee - Thái Phiên", content: "Lâu rồi mới ghé lại quán, kêu cũng khá nhiều đồ vì mình đi cùng tụi bạn. Quán vẫn thế, nhân viên phục vụ vẫn tận tình  mình gọi bingsu xoài, trà xanh, socola, dâu loại nào cũng ngon cả có điều trà xanh hơi nhạt, và cũng do bingsu lạnh quá nên bay mất mùi vị của trà xanh. Còn trà thì mình gọi trà dâu, lựu, táo, gừng nóng, trà uống ngon, đậm đà, trà lựu hơi chua một chút có lẽ do lựu mùa này chưa ngọt sẽ còn tiếp tục ủng hộ quán"},
#   {user_id: "3", title: "Chia sẻ cho các bạn quán Sông Hương - Đặc Sản Huế ", content: "Mình đi ăn đã nhiều quán bánh bèo, nậm, lọc...ở ĐN. Ngon có, dỡ có, đắt có, rẻ có...nói về độ ngon thì quán Hàng Me ở đường Trần Phú, nhưng quá đắt nên kg hợp với gđ mình lắm. Nói về đa dạng nhiều loại bánh là quán Vân ở đường Thanh Tịnh, quán Vân kg phải bánh huế và mình chỉ thích bánh bèo, ướt ở đây. Còn về bánh nậm phải nói quán Sông Hương ngon và rẻ, đúng bánh huế luôn : mỏng, nhân tôm thịt xay không có nấm, bột mềm và thơm, nước chấm rất ngon. Bánh nậm ở đây cũng ngon ghê, nhưng nước chấm kiểu huế mình không thích lắm. Ngon và rẻ."},
#   {user_id: "7", title: "Tô phở gà rất tuyệt tại Nhật Vy - Phở Hà Nội", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. Phở gà cảm thấy khá vừa miệng, gà dai ngon. Rau tươi xanh. Nói chung hài lòng sẽ ghé lại ^^"},
#
#   {user_id: "3", title: "Cảm thấy tuyệt vời cùng cửa hàng Bánh Năm", content: "Chiều thứ 7 ngày 23/5 tới, cửa hàng Bánh Năm đã khai trương địa điểm đầu tiên tại 151A Xô Viết Nghệ Tĩnh, phường 17, quận Bình Thạnh, Tp HCM. Mọi người ghé ủng hộ nhé  "},
#   {user_id: "2", title: "Cảm thấy ngon tại Quán bánh xèo Bà Dưỡng", content: "Thường ăn bánh xèo giá tầm 5k-10k, lần đầu nghe cái bánh xèo 20k thấy cũng là lạ, đến ăn xem nó thế nào. Đi 2 người, kêu 4 cái, đem ra dĩa 4 cái, thấy bánh nho nhỏ, nghĩ bụng 1 người ăn chắc cũng chưa no lắm. Nghĩ bụng là thế, 2 người ăn xong 3 cái là no.  Nước chấm 2 loại đều đậm đà. Bánh xèo chờ hơi lâu 1 chút. Có món bánh tráng thịt heo nghe nói cũng được, lần sau sẽ thử xem thế nào"},
#   {user_id: "7", title: "Rất ngon nhé - Nhật Vy - Phở Hà Nội", content: "Phở đậm chất Hà Nội. Thịt tái mềm, gầu ngon, nước trong vắt. Đang khuyến mãi nên tô to trà bá có 20k no nê. Lâu rồi mới ăn tô phở đúng vị. Quán rộng rãi, thoáng mát. Sẽ ghé nhiều lần."},
#   {user_id: "4", title: "Bún Đậu Cô Nhỏ thiên đường của mắm", content: "Minh đã đến đây nhiều lần giờ mới viết =)) Không gian thoáng mát, chỗ khá dễ tìm  Đồ ăn ngon, nước ép khá được , cơ mà hôm bữa đến ăn nó chua quá à  Giá thì đắt hơn quán khác 1 tí, phục vụ đồ ăn nhanh  Sẽ quay lại "},
#   {user_id: "5", title: " BlackBall - 32 Quang Trung, Hải Châu, Đà Nẵng", content: "Những món ăn cay là một phần không thể thiếu trong văn hóa ẩm thực Việt Nam, đem đến cho thực khách những trải nghiệm mới mẻ và khó quên.Hãy đến với cửa hàng BlackBall của chúng tôi, địa chỉ: 32 Quang Trung, Hải Châu, Đà Nẵng "},
#   {user_id: "2", title: "Ngon mà rẻ tại Ba Lép - Nhậu Bình Dân", content: "công nhận là ngon món hầu điéu với cua j đó đặc sản Nha Trang có 60k ngon bổ rẻ . ma sò điệp nướng mở hành thấy ai ăn cũng đầy đủ sao mình ăn thấy trớt quớt ko thay hành mở j hêt ( chăc tại keu sò nướng thôi) them món mực nua ma ham ăn ko chup . tong thiet hại 3 món 170k . nhắc lại cung còn thèm . ma gần nhà nua chứ đi có 5 phut la tới rồi quá thuận tiện . muốn an nhím biển thử mà hết rồi anh nhân viên kêu muon an đầy đủ phai di 4h chiều"},
#   {user_id: "7", title: "Cũng thưởng thức hải sải tại Quốc Huy 68 ", content: "Nhà hành này vừa mới khai trương luôn, nằm ngay con đường khá là đông khách sạn ngay sát biển luôn í. Mình tới đây cùng với bạn đi hai người thôi nên chỉ gọi lẩu và tôm tít xóc tỏi. Tôm tít phải nói là siêu to luôn nha, rất lf đáng đồng tiền bát gạo luôn ấy. Lẩu nhiều dễ sợ, tôm, mực, cá đều tươi rói hết. Nồi lẩu này phải 4 người ăn mới hết chứ 2 đứa mình ăn le lưỡi luôn."},
#   {user_id: "5", title: "Liferia Coffee - Thái Phiên", content: "Lâu rồi mới ghé lại quán, kêu cũng khá nhiều đồ vì mình đi cùng tụi bạn. Quán vẫn thế, nhân viên phục vụ vẫn tận tình  mình gọi bingsu xoài, trà xanh, socola, dâu loại nào cũng ngon cả có điều trà xanh hơi nhạt, và cũng do bingsu lạnh quá nên bay mất mùi vị của trà xanh. Còn trà thì mình gọi trà dâu, lựu, táo, gừng nóng, trà uống ngon, đậm đà, trà lựu hơi chua một chút có lẽ do lựu mùa này chưa ngọt sẽ còn tiếp tục ủng hộ quán"},
#   {user_id: "3", title: "Chia sẻ cho các bạn quán Sông Hương - Đặc Sản Huế ", content: "Mình đi ăn đã nhiều quán bánh bèo, nậm, lọc...ở ĐN. Ngon có, dỡ có, đắt có, rẻ có...nói về độ ngon thì quán Hàng Me ở đường Trần Phú, nhưng quá đắt nên kg hợp với gđ mình lắm. Nói về đa dạng nhiều loại bánh là quán Vân ở đường Thanh Tịnh, quán Vân kg phải bánh huế và mình chỉ thích bánh bèo, ướt ở đây. Còn về bánh nậm phải nói quán Sông Hương ngon và rẻ, đúng bánh huế luôn : mỏng, nhân tôm thịt xay không có nấm, bột mềm và thơm, nước chấm rất ngon. Bánh nậm ở đây cũng ngon ghê, nhưng nước chấm kiểu huế mình không thích lắm. Ngon và rẻ."},
#   {user_id: "7", title: "Tô phở gà rất tuyệt tại Nhật Vy - Phở Hà Nội", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. Phở gà cảm thấy khá vừa miệng, gà dai ngon. Rau tươi xanh. Nói chung hài lòng sẽ ghé lại ^^"},
#
#   {user_id: "3", title: "Cảm thấy tuyệt vời cùng cửa hàng Bánh Năm", content: "Chiều thứ 7 ngày 23/5 tới, cửa hàng Bánh Năm đã khai trương địa điểm đầu tiên tại 151A Xô Viết Nghệ Tĩnh, phường 17, quận Bình Thạnh, Tp HCM. Mọi người ghé ủng hộ nhé  "},
#   {user_id: "2", title: "Cảm thấy ngon tại Quán bánh xèo Bà Dưỡng", content: "Thường ăn bánh xèo giá tầm 5k-10k, lần đầu nghe cái bánh xèo 20k thấy cũng là lạ, đến ăn xem nó thế nào. Đi 2 người, kêu 4 cái, đem ra dĩa 4 cái, thấy bánh nho nhỏ, nghĩ bụng 1 người ăn chắc cũng chưa no lắm. Nghĩ bụng là thế, 2 người ăn xong 3 cái là no.  Nước chấm 2 loại đều đậm đà. Bánh xèo chờ hơi lâu 1 chút. Có món bánh tráng thịt heo nghe nói cũng được, lần sau sẽ thử xem thế nào"},
#   {user_id: "7", title: "Rất ngon nhé - Nhật Vy - Phở Hà Nội", content: "Phở đậm chất Hà Nội. Thịt tái mềm, gầu ngon, nước trong vắt. Đang khuyến mãi nên tô to trà bá có 20k no nê. Lâu rồi mới ăn tô phở đúng vị. Quán rộng rãi, thoáng mát. Sẽ ghé nhiều lần."},
#   {user_id: "4", title: "Bún Đậu Cô Nhỏ thiên đường của mắm", content: "Minh đã đến đây nhiều lần giờ mới viết =)) Không gian thoáng mát, chỗ khá dễ tìm  Đồ ăn ngon, nước ép khá được , cơ mà hôm bữa đến ăn nó chua quá à  Giá thì đắt hơn quán khác 1 tí, phục vụ đồ ăn nhanh  Sẽ quay lại "},
#   {user_id: "5", title: " BlackBall - 32 Quang Trung, Hải Châu, Đà Nẵng", content: "Những món ăn cay là một phần không thể thiếu trong văn hóa ẩm thực Việt Nam, đem đến cho thực khách những trải nghiệm mới mẻ và khó quên.Hãy đến với cửa hàng BlackBall của chúng tôi, địa chỉ: 32 Quang Trung, Hải Châu, Đà Nẵng "},
#   {user_id: "2", title: "Ngon mà rẻ tại Ba Lép - Nhậu Bình Dân", content: "công nhận là ngon món hầu điéu với cua j đó đặc sản Nha Trang có 60k ngon bổ rẻ . ma sò điệp nướng mở hành thấy ai ăn cũng đầy đủ sao mình ăn thấy trớt quớt ko thay hành mở j hêt ( chăc tại keu sò nướng thôi) them món mực nua ma ham ăn ko chup . tong thiet hại 3 món 170k . nhắc lại cung còn thèm . ma gần nhà nua chứ đi có 5 phut la tới rồi quá thuận tiện . muốn an nhím biển thử mà hết rồi anh nhân viên kêu muon an đầy đủ phai di 4h chiều"},
#   {user_id: "7", title: "Cũng thưởng thức hải sải tại Quốc Huy 68 ", content: "Nhà hành này vừa mới khai trương luôn, nằm ngay con đường khá là đông khách sạn ngay sát biển luôn í. Mình tới đây cùng với bạn đi hai người thôi nên chỉ gọi lẩu và tôm tít xóc tỏi. Tôm tít phải nói là siêu to luôn nha, rất lf đáng đồng tiền bát gạo luôn ấy. Lẩu nhiều dễ sợ, tôm, mực, cá đều tươi rói hết. Nồi lẩu này phải 4 người ăn mới hết chứ 2 đứa mình ăn le lưỡi luôn."},
#   {user_id: "5", title: "Liferia Coffee - Thái Phiên", content: "Lâu rồi mới ghé lại quán, kêu cũng khá nhiều đồ vì mình đi cùng tụi bạn. Quán vẫn thế, nhân viên phục vụ vẫn tận tình  mình gọi bingsu xoài, trà xanh, socola, dâu loại nào cũng ngon cả có điều trà xanh hơi nhạt, và cũng do bingsu lạnh quá nên bay mất mùi vị của trà xanh. Còn trà thì mình gọi trà dâu, lựu, táo, gừng nóng, trà uống ngon, đậm đà, trà lựu hơi chua một chút có lẽ do lựu mùa này chưa ngọt sẽ còn tiếp tục ủng hộ quán"},
#   {user_id: "3", title: "Chia sẻ cho các bạn quán Sông Hương - Đặc Sản Huế ", content: "Mình đi ăn đã nhiều quán bánh bèo, nậm, lọc...ở ĐN. Ngon có, dỡ có, đắt có, rẻ có...nói về độ ngon thì quán Hàng Me ở đường Trần Phú, nhưng quá đắt nên kg hợp với gđ mình lắm. Nói về đa dạng nhiều loại bánh là quán Vân ở đường Thanh Tịnh, quán Vân kg phải bánh huế và mình chỉ thích bánh bèo, ướt ở đây. Còn về bánh nậm phải nói quán Sông Hương ngon và rẻ, đúng bánh huế luôn : mỏng, nhân tôm thịt xay không có nấm, bột mềm và thơm, nước chấm rất ngon. Bánh nậm ở đây cũng ngon ghê, nhưng nước chấm kiểu huế mình không thích lắm. Ngon và rẻ."},
#   {user_id: "7", title: "Tô phở gà rất tuyệt tại Nhật Vy - Phở Hà Nội", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. Phở gà cảm thấy khá vừa miệng, gà dai ngon. Rau tươi xanh. Nói chung hài lòng sẽ ghé lại ^^"},
#
#   {user_id: "3", title: "Cảm thấy tuyệt vời cùng cửa hàng Bánh Năm", content: "Chiều thứ 7 ngày 23/5 tới, cửa hàng Bánh Năm đã khai trương địa điểm đầu tiên tại 151A Xô Viết Nghệ Tĩnh, phường 17, quận Bình Thạnh, Tp HCM. Mọi người ghé ủng hộ nhé  "},
#   {user_id: "2", title: "Cảm thấy ngon tại Quán bánh xèo Bà Dưỡng", content: "Thường ăn bánh xèo giá tầm 5k-10k, lần đầu nghe cái bánh xèo 20k thấy cũng là lạ, đến ăn xem nó thế nào. Đi 2 người, kêu 4 cái, đem ra dĩa 4 cái, thấy bánh nho nhỏ, nghĩ bụng 1 người ăn chắc cũng chưa no lắm. Nghĩ bụng là thế, 2 người ăn xong 3 cái là no.  Nước chấm 2 loại đều đậm đà. Bánh xèo chờ hơi lâu 1 chút. Có món bánh tráng thịt heo nghe nói cũng được, lần sau sẽ thử xem thế nào"},
#   {user_id: "7", title: "Rất ngon nhé - Nhật Vy - Phở Hà Nội", content: "Phở đậm chất Hà Nội. Thịt tái mềm, gầu ngon, nước trong vắt. Đang khuyến mãi nên tô to trà bá có 20k no nê. Lâu rồi mới ăn tô phở đúng vị. Quán rộng rãi, thoáng mát. Sẽ ghé nhiều lần."},
#   {user_id: "4", title: "Bún Đậu Cô Nhỏ thiên đường của mắm", content: "Minh đã đến đây nhiều lần giờ mới viết =)) Không gian thoáng mát, chỗ khá dễ tìm  Đồ ăn ngon, nước ép khá được , cơ mà hôm bữa đến ăn nó chua quá à  Giá thì đắt hơn quán khác 1 tí, phục vụ đồ ăn nhanh  Sẽ quay lại "},
#   {user_id: "5", title: " BlackBall - 32 Quang Trung, Hải Châu, Đà Nẵng", content: "Những món ăn cay là một phần không thể thiếu trong văn hóa ẩm thực Việt Nam, đem đến cho thực khách những trải nghiệm mới mẻ và khó quên.Hãy đến với cửa hàng BlackBall của chúng tôi, địa chỉ: 32 Quang Trung, Hải Châu, Đà Nẵng "},
#   {user_id: "2", title: "Ngon mà rẻ tại Ba Lép - Nhậu Bình Dân", content: "công nhận là ngon món hầu điéu với cua j đó đặc sản Nha Trang có 60k ngon bổ rẻ . ma sò điệp nướng mở hành thấy ai ăn cũng đầy đủ sao mình ăn thấy trớt quớt ko thay hành mở j hêt ( chăc tại keu sò nướng thôi) them món mực nua ma ham ăn ko chup . tong thiet hại 3 món 170k . nhắc lại cung còn thèm . ma gần nhà nua chứ đi có 5 phut la tới rồi quá thuận tiện . muốn an nhím biển thử mà hết rồi anh nhân viên kêu muon an đầy đủ phai di 4h chiều"},
#   {user_id: "7", title: "Cũng thưởng thức hải sải tại Quốc Huy 68 ", content: "Nhà hành này vừa mới khai trương luôn, nằm ngay con đường khá là đông khách sạn ngay sát biển luôn í. Mình tới đây cùng với bạn đi hai người thôi nên chỉ gọi lẩu và tôm tít xóc tỏi. Tôm tít phải nói là siêu to luôn nha, rất lf đáng đồng tiền bát gạo luôn ấy. Lẩu nhiều dễ sợ, tôm, mực, cá đều tươi rói hết. Nồi lẩu này phải 4 người ăn mới hết chứ 2 đứa mình ăn le lưỡi luôn."},
#   {user_id: "5", title: "Liferia Coffee - Thái Phiên", content: "Lâu rồi mới ghé lại quán, kêu cũng khá nhiều đồ vì mình đi cùng tụi bạn. Quán vẫn thế, nhân viên phục vụ vẫn tận tình  mình gọi bingsu xoài, trà xanh, socola, dâu loại nào cũng ngon cả có điều trà xanh hơi nhạt, và cũng do bingsu lạnh quá nên bay mất mùi vị của trà xanh. Còn trà thì mình gọi trà dâu, lựu, táo, gừng nóng, trà uống ngon, đậm đà, trà lựu hơi chua một chút có lẽ do lựu mùa này chưa ngọt sẽ còn tiếp tục ủng hộ quán"},
#   {user_id: "3", title: "Chia sẻ cho các bạn quán Sông Hương - Đặc Sản Huế ", content: "Mình đi ăn đã nhiều quán bánh bèo, nậm, lọc...ở ĐN. Ngon có, dỡ có, đắt có, rẻ có...nói về độ ngon thì quán Hàng Me ở đường Trần Phú, nhưng quá đắt nên kg hợp với gđ mình lắm. Nói về đa dạng nhiều loại bánh là quán Vân ở đường Thanh Tịnh, quán Vân kg phải bánh huế và mình chỉ thích bánh bèo, ướt ở đây. Còn về bánh nậm phải nói quán Sông Hương ngon và rẻ, đúng bánh huế luôn : mỏng, nhân tôm thịt xay không có nấm, bột mềm và thơm, nước chấm rất ngon. Bánh nậm ở đây cũng ngon ghê, nhưng nước chấm kiểu huế mình không thích lắm. Ngon và rẻ."},
#   {user_id: "7", title: "Tô phở gà rất tuyệt tại Nhật Vy - Phở Hà Nội", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. Phở gà cảm thấy khá vừa miệng, gà dai ngon. Rau tươi xanh. Nói chung hài lòng sẽ ghé lại ^^"},
#
#   ])
#
#
# Comment.create([
#   {user_id: "3", post_id: "2" , comment_id: "", content: "Quán ăn địa thế đẹp, bánh ngon, nước tương ngon, giá phải chăng, nhưng khâu phục vụ chăm sóc khách hàng còn hạn chế cần tốt hơn Chúc quán luôn thành công"},
#   {user_id: "5", post_id: "2" , comment_id: "", content: "Quán rộng, thoáng. Bánh xèo giòn, ngon, tôm thấm, rau giá đầy đủ, nước chấm tuyệt luôn. Nem lụi cây 5k ngon ghê luôn. Chỉ có đều rau sống ở đây mình không dám đụng luôn, chỉ ăn dưa leo, quán nên xem lại nhân viên rửa rau nhe! Sẽ tiếp tục ghé."},
#   {user_id: "7", post_id: "2" , comment_id: "", content: "Nge bạn bè cù rủ quán này ngon lắm mà mãi mới có dịp ghé.  Quán nằm ngay bờ hồ nên cũng khá thoáng. Bánh xèo nóng hổi mới ra khá giòn, ăn bánh xèo với thịt nướng là ngon nhất. Nem lụi thì mình thấy bình thường như mấy chỗ khác. Giá cả phù hợp."},
#   {user_id: "9", post_id: "2" , comment_id: "", content: "Cứ thèm bánh xèo tôm nhảy thì lại đến ngay quán này mà ăn. Quán sạch sẽ, nhìn thiện cảm, giá cả hợp lý, chất lượng, rất thích hợp cho gia đình hay bạn bè lâu ngày gặp nhau đến ăn :3"},
#   {user_id: "8", post_id: "3" , comment_id: "", content: "Thấy nhiều thịt . Ăn no nê đã luôn. Đúng vị phở Hà Nội."},
#   {user_id: "2", post_id: "3" , comment_id: "", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. "},
#   {user_id: "4", post_id: "3" , comment_id: "", content: "Ghé quán lần 2 rồi mà hôm nay mới chụp hình review. Quán hình như cũng mới mở không bao lâu, gia đình chủ quán người Hà Nội luôn nên ăn phở ở đây đúng chất Hà Nội luôn. Nước phở khá ngọt, thịt bò mềm. Tô to ăn no luôn. "},
#   {user_id: "7", post_id: "4" , comment_id: "", content: "Mình đã ăn ở đây vô số lần rồi, thích nhất là bún đậu mắm tôm và chả cá lã vọng. Lần này mình đi 2 người, gọi một mẹt bún đậu cỡ trung 60k ăn no lặt lè luôn :D Đồ ăn ngon, nhân viên nhiệt tình, không gian thoáng, rộng rãi. Sẽ ghé lại dài dài"},
#   {user_id: "2", post_id: "4" , comment_id: "", content: "Tổng thể thấy quá bình thường. Bún than để trên mẹt thì thành cục nhưng gắp lên thì rời rời. Mắm nhạt và không đậm vị. Thịt, lòng và chả thì ngội. Đậu khuôn được chiên đi chiên lại chứ không phải chiên mới nên lớp da dòn muốn rời ra ngoài."},
#   {user_id: "9", post_id: "4" , comment_id: "", content: "Mình thích không gian quán này vô cùng. Lối vào có hàng tre xanh rất mộc. Không gian khá thoáng rất mộc mạc. Quán này có cả thơ về quán viết bằng thư pháp đó.  Mình hôm bữa đi ăn lòng xào nghệ. Mình thấy một đĩa 45k theo mình thì hơi chát một tý."},
#   {user_id: "3", post_id: "4" , comment_id: "", content: "Mắm ngon, nhưng cho ít mắm quá, cứ xin thêm cũng ngại, hic hic, nói chung ăn tổng thể khá ngon"},
#   {user_id: "4", post_id: "4" , comment_id: "", content: "bún đậu cô nhỏ chất lượng đỉnh cao =]] mình đi cũng nhiều quán bún đậu nhưng thích nhất cái mẹt bún đậu to bự 3 người ăn,mẹt này mới là mẹt lớn chứ 90k/ mẹt này mà hôm nay làm hơi rời rạc tí, có lòng non,chả cốm,thịt da giòn,thịt ba chỉ"},
#   {user_id: "2", post_id: "4" , comment_id: "", content: "Đợt rồi có bạn giới thiệu quán này có bún đậu ngon nên mình cũng lon ton đi xem thế nào.  Quán xá từ cổng vào cũng khá dễ thương, mát mẻ và yên ắng, không quá lộn xộn.  Buổi chiều ngồi rất thích nhé.  Mẹt bún đậu lớn 90k đầy đặn, mắm ngon. "},
#   {user_id: "5", post_id: "6" , comment_id: "", content: "Mình đi ăn 4 người , 7 món, giá so với mặt bằng chung và với địa điểm của quán vậy là được. Mình thích nhất là món ốc tự nhiên hấp, vị ốc ngọt, tươi , tuy có con ăn nhẫn nhẫn , nhưng k có nước chấm cho món này, nhà mình ăn 2 đĩa."},
#   {user_id: "9", post_id: "6" , comment_id: "", content: "Mình quên một món nữa đó là tôm hấp. Không biết những hôm khác sao chứ mình ăn thấy tệ nhất món này, một đĩa chỉ vài con tôm nhỏ thôi, hấp lên đầu đen hết trơn ( k tươi j cả) , nói chung rất thất vọng món tôm ."},
#   {user_id: "6", post_id: "6" , comment_id: "", content: "Cuối tuần vừa rồi cùng tụi bạn dắt nhau qua đây nhậu, nói nhậu chứ toàn con gái không nên bọn nó ăn là chính. kaka."},
#   {user_id: "7", post_id: "7" , comment_id: "", content: "Quán Hải sản - Cơm bình dân.  Mấy đứa bạn mình ở nơi khác ra chơi nhân dịp lễ quán nào cũng đông nên bọn mình chọn đại quán này để vào ăn. Buổi trưa ngày lễ nên khá đông khách.  Hải sản ở đây khá tươi và ngon, giá cả cũng khá rẻi."},
#   {user_id: "2", post_id: "7" , comment_id: "", content: "ngày lễ, đợi đồ ăn lâu nhưng hên là vẫn còn bàn. Qua trễ nên còn ít đồ ăn. Không sao cả."},
#   {user_id: "9", post_id: "7" , comment_id: "", content: "Đường đến quán cực kì khó kiếm. Không thuận lời cho lắm về vị trí nhưng rất được về chất lượng hải sản, giá cả và phục vụ. Các loại hải sản ở đây đều đồng giá 60k nhưng rất đáng đồng tiền bát gạo. Một phần hải sản vừa nhiều vừa tươi."},
#   {user_id: "3", post_id: "7" , comment_id: "", content: "Hôm nay đi nhậu với mấy thằng bạn bên hội đá bóng, kéo qua chỗ này cho rẻ. Đồ ăn ngon làm nhanh. không gian rộng mà đông, nhân viên vài người thấy chạy bàn khùng cũng tội. Cá diêu hồng chiên mắm xoài ngon lắm, cá nhỏ thôi vì có 60k mà."},
#   {user_id: "4", post_id: "8" , comment_id: "", content: "Rảnh rỗi lại ghé Liferia vs nhỏ bạn uống nước và tám chuyện. Khách tối nay khá đông, ngồi ngoài nhìn xe chạy qua chạy lại cũng vui lắm. Nhân viên nhanh nhẹn, nhiệt tình. Quán này là quán ruột luôn rồi "},
#   {user_id: "2", post_id: "8" , comment_id: "", content: "Mới đầu tuần đã làm hai cử cafe ở Liferia rồi. Không gian đẹp, sang chảnh, nước ngon giá cả phù hợp. Nhân viên phục vụ nhanh nhẹn, vui vẻ với khách. Nói chung cảm nhận của mình về Liferia là tốt về mọi mặt "},
#   {user_id: "5", post_id: "8" , comment_id: "", content: "Tối chán quá thế là dắt nhau đi uống nước thôi. Trà dâu và trà táo rất thơm nhưng vị trà táo có vẻ gắt hơn nên hơi khó uống. Cốt bánh mềm, mịn. Bánh thơm và rất ngon. Không gian ở đây tuy nhỏ  nhưng khách đông không kém.  "},
#   {user_id: "9", post_id: "8" , comment_id: "", content: "Một trong những quán cafe thuộc tầm trung ở đà nẵng mà có nhiều chi nhánh nhất nhì trên địa bàn thành phố luôn. Quán được cái demo trang trí dễ thương và khá đẹp mắt. Menu đồ uống nhiều loại để lựa chọn từ nước uống, kem, bingsu các loại ."},
#   {user_id: "6", post_id: "9" , comment_id: "", content: "Mình kết bánh nậm lọc quán ni, luôn nóng hổi và ngon ghê, nhân thấm mặn mà. Ngoài bánh ra còn có hủ tiếu nam vang tuyệt vời nữa nì."},
#   {user_id: "7", post_id: "9" , comment_id: "", content: "Đà Nẵng đẹp quá, không khí trong lành nữa. Nghe nhỏ bạn đi du lịch đợt rồi giới thiệu quán ăn này. Mình ăn hủ tiếu nam vang, lạ và ngon quá. Ăn thử bánh nậm cũng ngo nữa, đặt 100 cái đem về làm quà. Phục vụ ở đây rất nhiệt tình và thân thiện."},
#   {user_id: "2", post_id: "9" , comment_id: "", content: "Trưa nay đi dự tiệc về, không ăn uống gì nhiều. Giờ mấy cô rủ lại đây nè. Bánh nậm lọc ở đây tuyệt vời, ăn không biết ngán lun. 3 cô mà kêu 6 dĩa bánh+ 3 bánh canh. Chén hết lun, hihi béo phì mất. Ngon."},
#
#   {user_id: "3", post_id: "12" , comment_id: "", content: "Quán ăn địa thế đẹp, bánh ngon, nước tương ngon, giá phải chăng, nhưng khâu phục vụ chăm sóc khách hàng còn hạn chế cần tốt hơn Chúc quán luôn thành công"},
#   {user_id: "5", post_id: "12" , comment_id: "", content: "Quán rộng, thoáng. Bánh xèo giòn, ngon, tôm thấm, rau giá đầy đủ, nước chấm tuyệt luôn. Nem lụi cây 5k ngon ghê luôn. Chỉ có đều rau sống ở đây mình không dám đụng luôn, chỉ ăn dưa leo, quán nên xem lại nhân viên rửa rau nhe! Sẽ tiếp tục ghé."},
#   {user_id: "7", post_id: "12" , comment_id: "", content: "Nge bạn bè cù rủ quán này ngon lắm mà mãi mới có dịp ghé.  Quán nằm ngay bờ hồ nên cũng khá thoáng. Bánh xèo nóng hổi mới ra khá giòn, ăn bánh xèo với thịt nướng là ngon nhất. Nem lụi thì mình thấy bình thường như mấy chỗ khác. Giá cả phù hợp."},
#   {user_id: "9", post_id: "12" , comment_id: "", content: "Cứ thèm bánh xèo tôm nhảy thì lại đến ngay quán này mà ăn. Quán sạch sẽ, nhìn thiện cảm, giá cả hợp lý, chất lượng, rất thích hợp cho gia đình hay bạn bè lâu ngày gặp nhau đến ăn :3"},
#   {user_id: "8", post_id: "13" , comment_id: "", content: "Thấy nhiều thịt . Ăn no nê đã luôn. Đúng vị phở Hà Nội."},
#   {user_id: "2", post_id: "13" , comment_id: "", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. "},
#   {user_id: "4", post_id: "13" , comment_id: "", content: "Ghé quán lần 2 rồi mà hôm nay mới chụp hình review. Quán hình như cũng mới mở không bao lâu, gia đình chủ quán người Hà Nội luôn nên ăn phở ở đây đúng chất Hà Nội luôn. Nước phở khá ngọt, thịt bò mềm. Tô to ăn no luôn. "},
#   {user_id: "7", post_id: "14" , comment_id: "", content: "Mình đã ăn ở đây vô số lần rồi, thích nhất là bún đậu mắm tôm và chả cá lã vọng. Lần này mình đi 2 người, gọi một mẹt bún đậu cỡ trung 60k ăn no lặt lè luôn :D Đồ ăn ngon, nhân viên nhiệt tình, không gian thoáng, rộng rãi. Sẽ ghé lại dài dài"},
#   {user_id: "2", post_id: "14" , comment_id: "", content: "Tổng thể thấy quá bình thường. Bún than để trên mẹt thì thành cục nhưng gắp lên thì rời rời. Mắm nhạt và không đậm vị. Thịt, lòng và chả thì ngội. Đậu khuôn được chiên đi chiên lại chứ không phải chiên mới nên lớp da dòn muốn rời ra ngoài."},
#   {user_id: "9", post_id: "14" , comment_id: "", content: "Mình thích không gian quán này vô cùng. Lối vào có hàng tre xanh rất mộc. Không gian khá thoáng rất mộc mạc. Quán này có cả thơ về quán viết bằng thư pháp đó.  Mình hôm bữa đi ăn lòng xào nghệ. Mình thấy một đĩa 45k theo mình thì hơi chát một tý."},
#   {user_id: "3", post_id: "14" , comment_id: "", content: "Mắm ngon, nhưng cho ít mắm quá, cứ xin thêm cũng ngại, hic hic, nói chung ăn tổng thể khá ngon"},
#   {user_id: "4", post_id: "14" , comment_id: "", content: "bún đậu cô nhỏ chất lượng đỉnh cao =]] mình đi cũng nhiều quán bún đậu nhưng thích nhất cái mẹt bún đậu to bự 3 người ăn,mẹt này mới là mẹt lớn chứ 90k/ mẹt này mà hôm nay làm hơi rời rạc tí, có lòng non,chả cốm,thịt da giòn,thịt ba chỉ"},
#   {user_id: "2", post_id: "14" , comment_id: "", content: "Đợt rồi có bạn giới thiệu quán này có bún đậu ngon nên mình cũng lon ton đi xem thế nào.  Quán xá từ cổng vào cũng khá dễ thương, mát mẻ và yên ắng, không quá lộn xộn.  Buổi chiều ngồi rất thích nhé.  Mẹt bún đậu lớn 90k đầy đặn, mắm ngon. "},
#   {user_id: "5", post_id: "16" , comment_id: "", content: "Mình đi ăn 4 người , 7 món, giá so với mặt bằng chung và với địa điểm của quán vậy là được. Mình thích nhất là món ốc tự nhiên hấp, vị ốc ngọt, tươi , tuy có con ăn nhẫn nhẫn , nhưng k có nước chấm cho món này, nhà mình ăn 2 đĩa."},
#   {user_id: "9", post_id: "16" , comment_id: "", content: "Mình quên một món nữa đó là tôm hấp. Không biết những hôm khác sao chứ mình ăn thấy tệ nhất món này, một đĩa chỉ vài con tôm nhỏ thôi, hấp lên đầu đen hết trơn ( k tươi j cả) , nói chung rất thất vọng món tôm ."},
#   {user_id: "6", post_id: "16" , comment_id: "", content: "Cuối tuần vừa rồi cùng tụi bạn dắt nhau qua đây nhậu, nói nhậu chứ toàn con gái không nên bọn nó ăn là chính. kaka."},
#   {user_id: "7", post_id: "17" , comment_id: "", content: "Quán Hải sản - Cơm bình dân.  Mấy đứa bạn mình ở nơi khác ra chơi nhân dịp lễ quán nào cũng đông nên bọn mình chọn đại quán này để vào ăn. Buổi trưa ngày lễ nên khá đông khách.  Hải sản ở đây khá tươi và ngon, giá cả cũng khá rẻi."},
#   {user_id: "2", post_id: "17" , comment_id: "", content: "ngày lễ, đợi đồ ăn lâu nhưng hên là vẫn còn bàn. Qua trễ nên còn ít đồ ăn. Không sao cả."},
#   {user_id: "9", post_id: "17" , comment_id: "", content: "Đường đến quán cực kì khó kiếm. Không thuận lời cho lắm về vị trí nhưng rất được về chất lượng hải sản, giá cả và phục vụ. Các loại hải sản ở đây đều đồng giá 60k nhưng rất đáng đồng tiền bát gạo. Một phần hải sản vừa nhiều vừa tươi."},
#   {user_id: "3", post_id: "17" , comment_id: "", content: "Hôm nay đi nhậu với mấy thằng bạn bên hội đá bóng, kéo qua chỗ này cho rẻ. Đồ ăn ngon làm nhanh. không gian rộng mà đông, nhân viên vài người thấy chạy bàn khùng cũng tội. Cá diêu hồng chiên mắm xoài ngon lắm, cá nhỏ thôi vì có 60k mà."},
#   {user_id: "4", post_id: "18" , comment_id: "", content: "Rảnh rỗi lại ghé Liferia vs nhỏ bạn uống nước và tám chuyện. Khách tối nay khá đông, ngồi ngoài nhìn xe chạy qua chạy lại cũng vui lắm. Nhân viên nhanh nhẹn, nhiệt tình. Quán này là quán ruột luôn rồi "},
#   {user_id: "2", post_id: "18" , comment_id: "", content: "Mới đầu tuần đã làm hai cử cafe ở Liferia rồi. Không gian đẹp, sang chảnh, nước ngon giá cả phù hợp. Nhân viên phục vụ nhanh nhẹn, vui vẻ với khách. Nói chung cảm nhận của mình về Liferia là tốt về mọi mặt "},
#   {user_id: "5", post_id: "18" , comment_id: "", content: "Tối chán quá thế là dắt nhau đi uống nước thôi. Trà dâu và trà táo rất thơm nhưng vị trà táo có vẻ gắt hơn nên hơi khó uống. Cốt bánh mềm, mịn. Bánh thơm và rất ngon. Không gian ở đây tuy nhỏ  nhưng khách đông không kém.  "},
#   {user_id: "9", post_id: "18" , comment_id: "", content: "Một trong những quán cafe thuộc tầm trung ở đà nẵng mà có nhiều chi nhánh nhất nhì trên địa bàn thành phố luôn. Quán được cái demo trang trí dễ thương và khá đẹp mắt. Menu đồ uống nhiều loại để lựa chọn từ nước uống, kem, bingsu các loại ."},
#   {user_id: "6", post_id: "19" , comment_id: "", content: "Mình kết bánh nậm lọc quán ni, luôn nóng hổi và ngon ghê, nhân thấm mặn mà. Ngoài bánh ra còn có hủ tiếu nam vang tuyệt vời nữa nì."},
#   {user_id: "7", post_id: "19" , comment_id: "", content: "Đà Nẵng đẹp quá, không khí trong lành nữa. Nghe nhỏ bạn đi du lịch đợt rồi giới thiệu quán ăn này. Mình ăn hủ tiếu nam vang, lạ và ngon quá. Ăn thử bánh nậm cũng ngo nữa, đặt 100 cái đem về làm quà. Phục vụ ở đây rất nhiệt tình và thân thiện."},
#   {user_id: "2", post_id: "19" , comment_id: "", content: "Trưa nay đi dự tiệc về, không ăn uống gì nhiều. Giờ mấy cô rủ lại đây nè. Bánh nậm lọc ở đây tuyệt vời, ăn không biết ngán lun. 3 cô mà kêu 6 dĩa bánh+ 3 bánh canh. Chén hết lun, hihi béo phì mất. Ngon."},
#
#   {user_id: "3", post_id: "22" , comment_id: "", content: "Quán ăn địa thế đẹp, bánh ngon, nước tương ngon, giá phải chăng, nhưng khâu phục vụ chăm sóc khách hàng còn hạn chế cần tốt hơn Chúc quán luôn thành công"},
#   {user_id: "5", post_id: "22" , comment_id: "", content: "Quán rộng, thoáng. Bánh xèo giòn, ngon, tôm thấm, rau giá đầy đủ, nước chấm tuyệt luôn. Nem lụi cây 5k ngon ghê luôn. Chỉ có đều rau sống ở đây mình không dám đụng luôn, chỉ ăn dưa leo, quán nên xem lại nhân viên rửa rau nhe! Sẽ tiếp tục ghé."},
#   {user_id: "7", post_id: "22" , comment_id: "", content: "Nge bạn bè cù rủ quán này ngon lắm mà mãi mới có dịp ghé.  Quán nằm ngay bờ hồ nên cũng khá thoáng. Bánh xèo nóng hổi mới ra khá giòn, ăn bánh xèo với thịt nướng là ngon nhất. Nem lụi thì mình thấy bình thường như mấy chỗ khác. Giá cả phù hợp."},
#   {user_id: "9", post_id: "22" , comment_id: "", content: "Cứ thèm bánh xèo tôm nhảy thì lại đến ngay quán này mà ăn. Quán sạch sẽ, nhìn thiện cảm, giá cả hợp lý, chất lượng, rất thích hợp cho gia đình hay bạn bè lâu ngày gặp nhau đến ăn :3"},
#   {user_id: "8", post_id: "23" , comment_id: "", content: "Thấy nhiều thịt . Ăn no nê đã luôn. Đúng vị phở Hà Nội."},
#   {user_id: "2", post_id: "23" , comment_id: "", content: "Mình ghé bên này mới mở nè. Sáng bán phở chiều bún đậu thì phải. Mình ghé buổi sáng gọi phở gà 30k 1 tô. Anh chủ quán phục vụ vui vẻ nhiệt tình. Quán không gian cũng thoải mái, trong hẻm nên mát mẻ và dễ chịu. "},
#   {user_id: "4", post_id: "23" , comment_id: "", content: "Ghé quán lần 2 rồi mà hôm nay mới chụp hình review. Quán hình như cũng mới mở không bao lâu, gia đình chủ quán người Hà Nội luôn nên ăn phở ở đây đúng chất Hà Nội luôn. Nước phở khá ngọt, thịt bò mềm. Tô to ăn no luôn. "},
#   {user_id: "7", post_id: "24" , comment_id: "", content: "Mình đã ăn ở đây vô số lần rồi, thích nhất là bún đậu mắm tôm và chả cá lã vọng. Lần này mình đi 2 người, gọi một mẹt bún đậu cỡ trung 60k ăn no lặt lè luôn :D Đồ ăn ngon, nhân viên nhiệt tình, không gian thoáng, rộng rãi. Sẽ ghé lại dài dài"},
#   {user_id: "2", post_id: "24" , comment_id: "", content: "Tổng thể thấy quá bình thường. Bún than để trên mẹt thì thành cục nhưng gắp lên thì rời rời. Mắm nhạt và không đậm vị. Thịt, lòng và chả thì ngội. Đậu khuôn được chiên đi chiên lại chứ không phải chiên mới nên lớp da dòn muốn rời ra ngoài."},
#   {user_id: "9", post_id: "24" , comment_id: "", content: "Mình thích không gian quán này vô cùng. Lối vào có hàng tre xanh rất mộc. Không gian khá thoáng rất mộc mạc. Quán này có cả thơ về quán viết bằng thư pháp đó.  Mình hôm bữa đi ăn lòng xào nghệ. Mình thấy một đĩa 45k theo mình thì hơi chát một tý."},
#   {user_id: "3", post_id: "24" , comment_id: "", content: "Mắm ngon, nhưng cho ít mắm quá, cứ xin thêm cũng ngại, hic hic, nói chung ăn tổng thể khá ngon"},
#   {user_id: "4", post_id: "24" , comment_id: "", content: "bún đậu cô nhỏ chất lượng đỉnh cao =]] mình đi cũng nhiều quán bún đậu nhưng thích nhất cái mẹt bún đậu to bự 3 người ăn,mẹt này mới là mẹt lớn chứ 90k/ mẹt này mà hôm nay làm hơi rời rạc tí, có lòng non,chả cốm,thịt da giòn,thịt ba chỉ"},
#   {user_id: "2", post_id: "24" , comment_id: "", content: "Đợt rồi có bạn giới thiệu quán này có bún đậu ngon nên mình cũng lon ton đi xem thế nào.  Quán xá từ cổng vào cũng khá dễ thương, mát mẻ và yên ắng, không quá lộn xộn.  Buổi chiều ngồi rất thích nhé.  Mẹt bún đậu lớn 90k đầy đặn, mắm ngon. "},
#   {user_id: "5", post_id: "26" , comment_id: "", content: "Mình đi ăn 4 người , 7 món, giá so với mặt bằng chung và với địa điểm của quán vậy là được. Mình thích nhất là món ốc tự nhiên hấp, vị ốc ngọt, tươi , tuy có con ăn nhẫn nhẫn , nhưng k có nước chấm cho món này, nhà mình ăn 2 đĩa."},
#   {user_id: "9", post_id: "26" , comment_id: "", content: "Mình quên một món nữa đó là tôm hấp. Không biết những hôm khác sao chứ mình ăn thấy tệ nhất món này, một đĩa chỉ vài con tôm nhỏ thôi, hấp lên đầu đen hết trơn ( k tươi j cả) , nói chung rất thất vọng món tôm ."},
#   {user_id: "6", post_id: "26" , comment_id: "", content: "Cuối tuần vừa rồi cùng tụi bạn dắt nhau qua đây nhậu, nói nhậu chứ toàn con gái không nên bọn nó ăn là chính. kaka."},
#   {user_id: "7", post_id: "27" , comment_id: "", content: "Quán Hải sản - Cơm bình dân.  Mấy đứa bạn mình ở nơi khác ra chơi nhân dịp lễ quán nào cũng đông nên bọn mình chọn đại quán này để vào ăn. Buổi trưa ngày lễ nên khá đông khách.  Hải sản ở đây khá tươi và ngon, giá cả cũng khá rẻi."},
#   {user_id: "2", post_id: "27" , comment_id: "", content: "ngày lễ, đợi đồ ăn lâu nhưng hên là vẫn còn bàn. Qua trễ nên còn ít đồ ăn. Không sao cả."},
#   {user_id: "9", post_id: "27" , comment_id: "", content: "Đường đến quán cực kì khó kiếm. Không thuận lời cho lắm về vị trí nhưng rất được về chất lượng hải sản, giá cả và phục vụ. Các loại hải sản ở đây đều đồng giá 60k nhưng rất đáng đồng tiền bát gạo. Một phần hải sản vừa nhiều vừa tươi."},
#   {user_id: "3", post_id: "27" , comment_id: "", content: "Hôm nay đi nhậu với mấy thằng bạn bên hội đá bóng, kéo qua chỗ này cho rẻ. Đồ ăn ngon làm nhanh. không gian rộng mà đông, nhân viên vài người thấy chạy bàn khùng cũng tội. Cá diêu hồng chiên mắm xoài ngon lắm, cá nhỏ thôi vì có 60k mà."},
#   {user_id: "4", post_id: "28" , comment_id: "", content: "Rảnh rỗi lại ghé Liferia vs nhỏ bạn uống nước và tám chuyện. Khách tối nay khá đông, ngồi ngoài nhìn xe chạy qua chạy lại cũng vui lắm. Nhân viên nhanh nhẹn, nhiệt tình. Quán này là quán ruột luôn rồi "},
#   {user_id: "2", post_id: "28" , comment_id: "", content: "Mới đầu tuần đã làm hai cử cafe ở Liferia rồi. Không gian đẹp, sang chảnh, nước ngon giá cả phù hợp. Nhân viên phục vụ nhanh nhẹn, vui vẻ với khách. Nói chung cảm nhận của mình về Liferia là tốt về mọi mặt "},
#   {user_id: "5", post_id: "28" , comment_id: "", content: "Tối chán quá thế là dắt nhau đi uống nước thôi. Trà dâu và trà táo rất thơm nhưng vị trà táo có vẻ gắt hơn nên hơi khó uống. Cốt bánh mềm, mịn. Bánh thơm và rất ngon. Không gian ở đây tuy nhỏ  nhưng khách đông không kém.  "},
#   {user_id: "9", post_id: "28" , comment_id: "", content: "Một trong những quán cafe thuộc tầm trung ở đà nẵng mà có nhiều chi nhánh nhất nhì trên địa bàn thành phố luôn. Quán được cái demo trang trí dễ thương và khá đẹp mắt. Menu đồ uống nhiều loại để lựa chọn từ nước uống, kem, bingsu các loại ."},
#   {user_id: "6", post_id: "29" , comment_id: "", content: "Mình kết bánh nậm lọc quán ni, luôn nóng hổi và ngon ghê, nhân thấm mặn mà. Ngoài bánh ra còn có hủ tiếu nam vang tuyệt vời nữa nì."},
#   {user_id: "7", post_id: "29" , comment_id: "", content: "Đà Nẵng đẹp quá, không khí trong lành nữa. Nghe nhỏ bạn đi du lịch đợt rồi giới thiệu quán ăn này. Mình ăn hủ tiếu nam vang, lạ và ngon quá. Ăn thử bánh nậm cũng ngo nữa, đặt 100 cái đem về làm quà. Phục vụ ở đây rất nhiệt tình và thân thiện."},
#   {user_id: "2", post_id: "29" , comment_id: "", content: "Trưa nay đi dự tiệc về, không ăn uống gì nhiều. Giờ mấy cô rủ lại đây nè. Bánh nậm lọc ở đây tuyệt vời, ăn không biết ngán lun. 3 cô mà kêu 6 dĩa bánh+ 3 bánh canh. Chén hết lun, hihi béo phì mất. Ngon."},
#
#   ])
#
# Like.create([
#   {user_id: "2", post_id: "1", isLike: "1"},
#   {user_id: "2", post_id: "2", isLike: "1"},
#   {user_id: "2", post_id: "3", isLike: "1"},
#   # {user_id: "2", post_id: "4", isLike: "1"},
#   {user_id: "2", post_id: "5", isLike: "1"},
#   {user_id: "2", post_id: "6", isLike: "1"},
#   {user_id: "2", post_id: "7", isLike: "1"},
#   {user_id: "2", post_id: "8", isLike: "1"},
#   # {user_id: "2", post_id: "9", isLike: "1"},
#   {user_id: "2", post_id: "10", isLike: "1"},
#   {user_id: "2", post_id: "11", isLike: "1"},
#   {user_id: "2", post_id: "12", isLike: "1"},
#   {user_id: "2", post_id: "13", isLike: "1"},
#   {user_id: "2", post_id: "14", isLike: "1"},
#   {user_id: "2", post_id: "15", isLike: "1"},
#   {user_id: "2", post_id: "16", isLike: "1"},
#   {user_id: "2", post_id: "17", isLike: "1"},
#   {user_id: "2", post_id: "18", isLike: "1"},
#   # {user_id: "2", post_id: "19", isLike: "1"},
#   {user_id: "2", post_id: "20", isLike: "1"},
#
#   {user_id: "3", post_id: "1", isLike: "1"},
#   {user_id: "3", post_id: "2", isLike: "1"},
#   {user_id: "3", post_id: "3", isLike: "1"},
#   {user_id: "3", post_id: "4", isLike: "1"},
#   {user_id: "3", post_id: "5", isLike: "1"},
#   # {user_id: "3", post_id: "6", isLike: "1"},
#   {user_id: "3", post_id: "7", isLike: "1"},
#   {user_id: "3", post_id: "8", isLike: "1"},
#   {user_id: "3", post_id: "9", isLike: "1"},
#   {user_id: "3", post_id: "10", isLike: "1"},
#   {user_id: "3", post_id: "11", isLike: "1"},
#   {user_id: "3", post_id: "12", isLike: "1"},
#   {user_id: "3", post_id: "13", isLike: "1"},
#   {user_id: "3", post_id: "14", isLike: "1"},
#   # {user_id: "3", post_id: "15", isLike: "1"},
#   {user_id: "3", post_id: "16", isLike: "1"},
#   {user_id: "3", post_id: "17", isLike: "1"},
#   {user_id: "3", post_id: "18", isLike: "1"},
#   {user_id: "3", post_id: "19", isLike: "1"},
#   {user_id: "3", post_id: "20", isLike: "1"},
#
#   {user_id: "4", post_id: "1", isLike: "1"},
#   # {user_id: "4", post_id: "2", isLike: "1"},
#   {user_id: "4", post_id: "3", isLike: "1"},
#   {user_id: "4", post_id: "4", isLike: "1"},
#   {user_id: "4", post_id: "5", isLike: "1"},
#   # {user_id: "4", post_id: "6", isLike: "1"},
#   {user_id: "4", post_id: "7", isLike: "1"},
#   {user_id: "4", post_id: "8", isLike: "1"},
#   {user_id: "4", post_id: "9", isLike: "1"},
#   {user_id: "4", post_id: "10", isLike: "1"},
#   {user_id: "4", post_id: "11", isLike: "1"},
#   {user_id: "4", post_id: "12", isLike: "1"},
#   {user_id: "4", post_id: "13", isLike: "1"},
#   # {user_id: "4", post_id: "14", isLike: "1"},
#   {user_id: "4", post_id: "15", isLike: "1"},
#   # {user_id: "4", post_id: "16", isLike: "1"},
#   {user_id: "4", post_id: "17", isLike: "1"},
#   {user_id: "4", post_id: "18", isLike: "1"},
#   {user_id: "4", post_id: "19", isLike: "1"},
#   {user_id: "4", post_id: "20", isLike: "1"},
#
#   {user_id: "5", post_id: "1", isLike: "1"},
#   {user_id: "5", post_id: "2", isLike: "1"},
#   # {user_id: "5", post_id: "3", isLike: "1"},
#   {user_id: "5", post_id: "4", isLike: "1"},
#   {user_id: "5", post_id: "5", isLike: "1"},
#   # {user_id: "5", post_id: "6", isLike: "1"},
#   {user_id: "5", post_id: "7", isLike: "1"},
#   {user_id: "5", post_id: "8", isLike: "1"},
#   {user_id: "5", post_id: "9", isLike: "1"},
#   {user_id: "5", post_id: "10", isLike: "1"},
#   {user_id: "5", post_id: "11", isLike: "1"},
#   {user_id: "5", post_id: "12", isLike: "1"},
#   # {user_id: "5", post_id: "13", isLike: "1"},
#   {user_id: "5", post_id: "14", isLike: "1"},
#   {user_id: "5", post_id: "15", isLike: "1"},
#   # {user_id: "5", post_id: "16", isLike: "1"},
#   {user_id: "5", post_id: "17", isLike: "1"},
#   {user_id: "5", post_id: "18", isLike: "1"},
#   {user_id: "5", post_id: "19", isLike: "1"},
#   {user_id: "5", post_id: "20", isLike: "1"},
#
#   # {user_id: "6", post_id: "1", isLike: "1"},
#   {user_id: "6", post_id: "2", isLike: "1"},
#   {user_id: "6", post_id: "3", isLike: "1"},
#   {user_id: "6", post_id: "4", isLike: "1"},
#   # {user_id: "6", post_id: "5", isLike: "1"},
#   {user_id: "6", post_id: "6", isLike: "1"},
#   {user_id: "6", post_id: "7", isLike: "1"},
#   {user_id: "6", post_id: "8", isLike: "1"},
#   {user_id: "6", post_id: "9", isLike: "1"},
#   # {user_id: "6", post_id: "10", isLike: "1"},
#   {user_id: "6", post_id: "11", isLike: "1"},
#   {user_id: "6", post_id: "12", isLike: "1"},
#   # {user_id: "6", post_id: "13", isLike: "1"},
#   {user_id: "6", post_id: "14", isLike: "1"},
#   {user_id: "6", post_id: "15", isLike: "1"},
#   {user_id: "6", post_id: "16", isLike: "1"},
#   # {user_id: "6", post_id: "17", isLike: "1"},
#   {user_id: "6", post_id: "18", isLike: "1"},
#   {user_id: "6", post_id: "19", isLike: "1"},
#   {user_id: "6", post_id: "20", isLike: "1"},
#
#   {user_id: "7", post_id: "1", isLike: "1"},
#   {user_id: "7", post_id: "2", isLike: "1"},
#   {user_id: "7", post_id: "3", isLike: "1"},
#   # {user_id: "7", post_id: "4", isLike: "1"},
#   {user_id: "7", post_id: "5", isLike: "1"},
#   # {user_id: "7", post_id: "6", isLike: "1"},
#   {user_id: "7", post_id: "7", isLike: "1"},
#   {user_id: "7", post_id: "8", isLike: "1"},
#   {user_id: "7", post_id: "9", isLike: "1"},
#   {user_id: "7", post_id: "10", isLike: "1"},
#   {user_id: "7", post_id: "11", isLike: "1"},
#   {user_id: "7", post_id: "12", isLike: "1"},
#   {user_id: "7", post_id: "13", isLike: "1"},
#   {user_id: "7", post_id: "14", isLike: "1"},
#   # {user_id: "7", post_id: "15", isLike: "1"},
#   {user_id: "7", post_id: "16", isLike: "1"},
#   {user_id: "7", post_id: "17", isLike: "1"},
#   {user_id: "7", post_id: "18", isLike: "1"},
#   {user_id: "7", post_id: "19", isLike: "1"},
#   {user_id: "7", post_id: "20", isLike: "1"},
#
#   {user_id: "8", post_id: "1", isLike: "1"},
#   # {user_id: "8", post_id: "2", isLike: "1"},
#   {user_id: "8", post_id: "3", isLike: "1"},
#   {user_id: "8", post_id: "4", isLike: "1"},
#   {user_id: "8", post_id: "5", isLike: "1"},
#   {user_id: "8", post_id: "6", isLike: "1"},
#   {user_id: "8", post_id: "7", isLike: "1"},
#   {user_id: "8", post_id: "8", isLike: "1"},
#   # {user_id: "8", post_id: "9", isLike: "1"},
#   {user_id: "8", post_id: "10", isLike: "1"},
#   {user_id: "8", post_id: "11", isLike: "1"},
#   {user_id: "8", post_id: "12", isLike: "1"},
#   # {user_id: "8", post_id: "13", isLike: "1"},
#   {user_id: "8", post_id: "14", isLike: "1"},
#   {user_id: "8", post_id: "15", isLike: "1"},
#   # {user_id: "8", post_id: "16", isLike: "1"},
#   {user_id: "8", post_id: "17", isLike: "1"},
#   {user_id: "8", post_id: "18", isLike: "1"},
#   {user_id: "8", post_id: "19", isLike: "1"},
#   {user_id: "8", post_id: "20", isLike: "1"},
#
#   {user_id: "9", post_id: "1", isLike: "1"},
#   {user_id: "9", post_id: "2", isLike: "1"},
#   {user_id: "9", post_id: "3", isLike: "1"},
#   # {user_id: "9", post_id: "4", isLike: "1"},
#   {user_id: "9", post_id: "5", isLike: "1"},
#   {user_id: "9", post_id: "6", isLike: "1"},
#   {user_id: "9", post_id: "7", isLike: "1"},
#   {user_id: "9", post_id: "8", isLike: "1"},
#   # {user_id: "9", post_id: "9", isLike: "1"},
#   {user_id: "9", post_id: "10", isLike: "1"},
#   {user_id: "9", post_id: "11", isLike: "1"},
#   {user_id: "9", post_id: "12", isLike: "1"},
#   {user_id: "9", post_id: "13", isLike: "1"},
#   {user_id: "9", post_id: "14", isLike: "1"},
#   {user_id: "9", post_id: "15", isLike: "1"},
#   {user_id: "9", post_id: "16", isLike: "1"},
#   {user_id: "9", post_id: "17", isLike: "1"},
#   # {user_id: "9", post_id: "18", isLike: "1"},
#   {user_id: "9", post_id: "19", isLike: "1"},
#   {user_id: "9", post_id: "20", isLike: "1"},
#
#
#   ])
#
# Food.create([
#   {restaurant_id: 6, kind: "eat", name: "Ram cuốn", price: "60000", image_file_name: "monan.jpg", image_content_type: "image/jpeg", image_file_size: "376172"},
#   {restaurant_id: 6, kind: "eat", name: "Bánh xèo", price: "40000", image_file_name: "monan1.jpg", image_content_type: "image/jpeg", image_file_size: "255908"},
#   {restaurant_id: 6, kind: "eat", name: "Bún giò", price: "20000", image_file_name: "monan4.jpg", image_content_type: "image/jpeg", image_file_size: "205441"},
#   {restaurant_id: 6, kind: "eat", name: "Mỳ cay", price: "35000", image_file_name: "monan7.jpg", image_content_type: "image/jpeg", image_file_size: "219698"},
#   {restaurant_id: 6, kind: "eat", name: "Chân gà nướng", price: "60000"},
#   {restaurant_id: 6, kind: "eat", name: "Sứa trộn", price: "40000", image_file_name: "monan8.jpg", image_content_type: "image/jpeg", image_file_size: "705437"},
#   {restaurant_id: 6, kind: "eat", name: "Gà quay", price: "130000", image_file_name: "monan10.png", image_content_type: "image/jpeg", image_file_size: "2300689"},
#   {restaurant_id: 6, kind: "eat", name: "Heo nướng lá lốt", price: "60000", image_file_name: "monan13.jpg", image_content_type: "image/jpeg", image_file_size: "250315"},
#   {restaurant_id: 6, kind: "eat", name: "Đuông dừa", price: "100000", image_file_name: "monan17.jpg", image_content_type: "image/jpeg", image_file_size: "83658"},
#   {restaurant_id: 6, kind: "eat", name: "Chả cá", price: "60000", image_file_name: "monan19.jpg", image_content_type: "image/jpeg", image_file_size: "1352121"},
#   {restaurant_id: 6, kind: "eat", name: "Lẩu gà", price: "150000", image_file_name: "monan23.jpg", image_content_type: "image/jpeg", image_file_size: "506845"},
#   {restaurant_id: 6, kind: "eat", name: "Mỳ ý", price: "60000", image_file_name: "monan26.jpg", image_content_type: "image/jpeg", image_file_size: "599580"},
#   {restaurant_id: 6, kind: "eat", name: "Mực nướng", price: "60000", image_file_name: "monan27.jpg", image_content_type: "image/jpeg", image_file_size: "795942"},
#   {restaurant_id: 6, kind: "eat", name: "Chim cút rô ti", price: "70000", image_file_name: "monan28.jpg", image_content_type: "image/jpeg", image_file_size: "241757"},
#   {restaurant_id: 6, kind: "eat", name: "Gà luộc", price: "140000", image_file_name: "monan41.jpg", image_content_type: "image/jpeg", image_file_size: "71395"},
#   {restaurant_id: 6, kind: "drink", name: "Heineken", price: "20000", image_file_name: "heineken.jpg", image_content_type: "image/jpeg", image_file_size: "145652"},
#   {restaurant_id: 6, kind: "drink", name: "Beer Sài Gòn", price: "15000", image_file_name: "saigon.JPG", image_content_type: "image/jpeg", image_file_size: "6632096"},
#   {restaurant_id: 6, kind: "drink", name: "Beer Tiger", price: "15000", image_file_name: "tiger.jpg", image_content_type: "image/jpeg", image_file_size: "322617"},
#   {restaurant_id: 6, kind: "drink", name: "Beer Larue", price: "13000", image_file_name: "larue.jpg", image_content_type: "image/jpeg", image_file_size: "530584"},
#   {restaurant_id: 6, kind: "drink", name: "Pepsi", price: "10000", image_file_name: "douongpepsi.jpg", image_content_type: "image/jpeg", image_file_size: "668851"},
#   {restaurant_id: 6, kind: "drink", name: "Nước dừa", price: "25000", image_file_name: "douong12.jpg", image_content_type: "image/jpeg", image_file_size: "1103877"},
#   {restaurant_id: 6, kind: "drink", name: "Sinh tố bơ", price: "20000", image_file_name: "douong10.jpg", image_content_type: "image/jpeg", image_file_size: "403014"},
#   {restaurant_id: 6, kind: "drink", name: "Cam vắt", price: "30000", image_file_name: "douong6.jpg", image_content_type: "image/jpeg", image_file_size: "493622"},
#   {restaurant_id: 6, kind: "drink", name: "Cà phê sữa sài gòn", price: "15000", image_file_name: "douong3.jpg", image_content_type: "image/jpeg", image_file_size: "156767"},
#   {restaurant_id: 6, kind: "drink", name: "Cà phê đen", price: "10000"},
#
#   {restaurant_id: 2, kind: "eat", name: "Heo nướng lá lốt", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Đuông dừa", price: "100000"},
#   {restaurant_id: 2, kind: "eat", name: "Chả cá", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Lẩu gà", price: "150000"},
#   {restaurant_id: 2, kind: "eat", name: "Mỳ ý", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Mực nướng", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Chim cút rô ti", price: "70000"},
#   {restaurant_id: 2, kind: "eat", name: "Gà luộc", price: "140000"},
#   {restaurant_id: 2, kind: "eat", name: "Ram cuốn", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Bánh xèo", price: "40000"},
#   {restaurant_id: 2, kind: "eat", name: "Bún giò", price: "20000"},
#   {restaurant_id: 2, kind: "eat", name: "Mỳ cay", price: "35000"},
#   {restaurant_id: 2, kind: "eat", name: "Chân gà nướng", price: "60000"},
#   {restaurant_id: 2, kind: "eat", name: "Sứa trộn", price: "40000"},
#   {restaurant_id: 2, kind: "eat", name: "Gà quay", price: "130000"},
#   {restaurant_id: 2, kind: "drink", name: "Heineken", price: "20000"},
#   {restaurant_id: 2, kind: "drink", name: "Beer Sài Gòn", price: "15000"},
#   {restaurant_id: 2, kind: "drink", name: "Beer Tiger", price: "15000"},
#   {restaurant_id: 2, kind: "drink", name: "Beer Larue", price: "13000"},
#   {restaurant_id: 2, kind: "drink", name: "Pepsi", price: "10000"},
#   {restaurant_id: 2, kind: "drink", name: "Nước dừa", price: "25000"},
#   {restaurant_id: 2, kind: "drink", name: "Sinh tố bơ", price: "20000"},
#   {restaurant_id: 2, kind: "drink", name: "Cam vắt", price: "30000"},
#   {restaurant_id: 2, kind: "drink", name: "Cà phê sữa sài gòn", price: "15000"},
#   {restaurant_id: 2, kind: "drink", name: "Cà phê đen", price: "10000"},
#
#
#   {restaurant_id: 4, kind: "eat", name: "Heo nướng lá lốt", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Đuông dừa", price: "100000"},
#   {restaurant_id: 4, kind: "eat", name: "Chả cá", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Lẩu gà", price: "150000"},
#   {restaurant_id: 4, kind: "eat", name: "Mỳ ý", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Mực nướng", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Chim cút rô ti", price: "70000"},
#   {restaurant_id: 4, kind: "eat", name: "Gà luộc", price: "140000"},
#   {restaurant_id: 4, kind: "eat", name: "Ram cuốn", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Bánh xèo", price: "40000"},
#   {restaurant_id: 4, kind: "eat", name: "Bún giò", price: "20000"},
#   {restaurant_id: 4, kind: "eat", name: "Mỳ cay", price: "35000"},
#   {restaurant_id: 4, kind: "eat", name: "Chân gà nướng", price: "60000"},
#   {restaurant_id: 4, kind: "eat", name: "Sứa trộn", price: "40000"},
#   {restaurant_id: 4, kind: "eat", name: "Gà quay", price: "130000"},
#   {restaurant_id: 4, kind: "drink", name: "Heineken", price: "20000"},
#   {restaurant_id: 4, kind: "drink", name: "Beer Sài Gòn", price: "15000"},
#   {restaurant_id: 4, kind: "drink", name: "Beer Tiger", price: "15000"},
#   {restaurant_id: 4, kind: "drink", name: "Beer Larue", price: "13000"},
#   {restaurant_id: 4, kind: "drink", name: "Pepsi", price: "10000"},
#   {restaurant_id: 4, kind: "drink", name: "Nước dừa", price: "25000"},
#   {restaurant_id: 4, kind: "drink", name: "Sinh tố bơ", price: "20000"},
#   {restaurant_id: 4, kind: "drink", name: "Cam vắt", price: "30000"},
#   {restaurant_id: 4, kind: "drink", name: "Cà phê sữa sài gòn", price: "15000"},
#   {restaurant_id: 4, kind: "drink", name: "Cà phê đen", price: "10000"},
#
#   ])

# Review.create([
#   {user_id: "2", restaurant_id: "2", rating: "2", content: "bad"},
#   {user_id: "2", restaurant_id: "4", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "2", restaurant_id: "6", rating: "4", content: "good"},
#   {user_id: "2", restaurant_id: "8", rating: "3", content: ""},
#   {user_id: "2", restaurant_id: "10", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "2", restaurant_id: "12", rating: "2", content: ""},
#   {user_id: "2", restaurant_id: "14", rating: "2", content: "bad"},
#   {user_id: "2", restaurant_id: "16", rating: "3", content: ""},
#   {user_id: "2", restaurant_id: "18", rating: "4", content: ""},
#   {user_id: "2", restaurant_id: "20", rating: "5", content: ""},
#   # {user_id: "2", restaurant_id: "22", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "24", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "26", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "28", rating: "", content: ""},
#   {user_id: "2", restaurant_id: "30", rating: "1", content: ""},
#   {user_id: "2", restaurant_id: "31",  rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "2", restaurant_id: "32", rating: "2", content: ""},
#   {user_id: "2", restaurant_id: "33", rating: "2", content: "bad"},
#   {user_id: "2", restaurant_id: "34", rating: "3", content: ""},
#   {user_id: "2", restaurant_id: "35", rating: "4", content: ""},
#   {user_id: "2", restaurant_id: "32", rating: "1", content: ""},
#   {user_id: "2", restaurant_id: "33", rating: "2", content: "bad"},
#   {user_id: "2", restaurant_id: "34", rating: "4", content: ""},
#   {user_id: "2", restaurant_id: "35", rating: "4", content: ""},
#   {user_id: "2", restaurant_id: "36",  rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "2", restaurant_id: "37", rating: "2", content: ""},
#   {user_id: "2", restaurant_id: "38", rating: "4", content: "good"},
#   {user_id: "2", restaurant_id: "39", rating: "2", content: "bad"},
#   {user_id: "2", restaurant_id: "40", rating: "4", content: ""},
#   # {user_id: "2", restaurant_id: "41", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "42", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "43", rating: "", content: ""},
#   # {user_id: "2", restaurant_id: "44", rating: "", content: ""},
#   {user_id: "2", restaurant_id: "45", rating: "2", content: ""},
#   {user_id: "2", restaurant_id: "46", rating: "6", content: ""},
#
#
#   {user_id: "3", restaurant_id: "2",  rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "4", rating: "4", content: ""},
#   {user_id: "3", restaurant_id: "6", rating: "5", content: ""},
#   {user_id: "3", restaurant_id: "8", rating: "2", content: "bad"},
#   # {user_id: "3", restaurant_id: "10", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "12", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "14", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "16", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "18", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "20", rating: "", content: ""},
#   {user_id: "2", restaurant_id: "22", rating: "4", content: ""},
#   {user_id: "3", restaurant_id: "24",  rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "26", rating: "3", content: ""},
#   {user_id: "3", restaurant_id: "28", rating: "4", content: "good"},
#   {user_id: "3", restaurant_id: "30", rating: "2", content: ""},
#   {user_id: "3", restaurant_id: "31", rating: "5", content: ""},
#   # {user_id: "3", restaurant_id: "32", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "33", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "34", rating: "", content: ""},
#   # {user_id: "3", restaurant_id: "35", rating: "", content: ""},
#   {user_id: "3", restaurant_id: "32", rating: "4", content: ""},
#   {user_id: "3", restaurant_id: "33", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "34", rating: "5", content: ""},
#   {user_id: "3", restaurant_id: "35", rating: "2", content: "bad"},
#   {user_id: "3", restaurant_id: "36", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "37", rating: "3", content: ""},
#   {user_id: "3", restaurant_id: "38", rating: "4", content: "good"},
#   {user_id: "3", restaurant_id: "39", rating: "5", content: ""},
#   {user_id: "3", restaurant_id: "40", rating: "4", content: ""},
#   {user_id: "3", restaurant_id: "41", rating: "2", content: "bad"},
#   {user_id: "3", restaurant_id: "42", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "43", rating: "3", content: ""},
#   {user_id: "3", restaurant_id: "44", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "3", restaurant_id: "45", rating: "2", content: ""},
#   {user_id: "3", restaurant_id: "46", rating: "5", content: ""},
#
#   {user_id: "4", restaurant_id: "2", rating: "4", content: ""},
#   # {user_id: "4", restaurant_id: "4", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "6", rating: "", content: ""},
#   {user_id: "4", restaurant_id: "8", rating: "2", content: "bad"},
#   {user_id: "4", restaurant_id: "10", rating: "3", content: ""},
#   {user_id: "4", restaurant_id: "12", rating: "4", content: "good"},
#   {user_id: "4", restaurant_id: "14", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "4", restaurant_id: "16", rating: "2", content: ""},
#   {user_id: "4", restaurant_id: "18", rating: "4", content: "good"},
#   {user_id: "4", restaurant_id: "20", rating: "4", content: ""},
#   {user_id: "4", restaurant_id: "22", rating: "2", content: "bad"},
#   {user_id: "4", restaurant_id: "24", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "4", restaurant_id: "26", rating: "5", content: ""},
#   {user_id: "4", restaurant_id: "28", rating: "2", content: ""},
#   # {user_id: "4", restaurant_id: "30", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "31", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "32", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "33", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "34", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "35", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "32", rating: "", content: ""},
#   # {user_id: "4", restaurant_id: "33", rating: "", content: ""},
#   {user_id: "4", restaurant_id: "34", rating: "3", content: ""},
#   {user_id: "4", restaurant_id: "35", rating: "4", content: ""},
#   {user_id: "4", restaurant_id: "36", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "4", restaurant_id: "37", rating: "5", content: ""},
#   {user_id: "4", restaurant_id: "38", rating: "2", content: ""},
#   {user_id: "4", restaurant_id: "39", rating: "2", content: "bad"},
#   {user_id: "4", restaurant_id: "40", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "4", restaurant_id: "41", rating: "2", content: "bad"},
#   {user_id: "4", restaurant_id: "42", rating: "3", content: ""},
#   {user_id: "4", restaurant_id: "43",rating: "4", content: "good"},
#   {user_id: "4", restaurant_id: "44", rating: "5", content: ""},
#   {user_id: "4", restaurant_id: "45", rating: "4", content: ""},
#   {user_id: "4", restaurant_id: "46", rating: "3", content: ""},
#
#
#   {user_id: "5", restaurant_id: "2", rating: "2", content: ""},
#   {user_id: "5", restaurant_id: "4", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "6", rating: "5", content: "Thật tuyệt vời"},
#   # {user_id: "5", restaurant_id: "8", rating: "", content: ""},
#   # {user_id: "5", restaurant_id: "10", rating: "", content: ""},
#   # {user_id: "5", restaurant_id: "12", rating: "", content: ""},
#   {user_id: "5", restaurant_id: "14", rating: "4", content: ""},
#   {user_id: "5", restaurant_id: "16", rating: "2", content: "bad"},
#   {user_id: "5", restaurant_id: "18", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "20", rating: "5", content: ""},
#   {user_id: "5", restaurant_id: "22", rating: "4", content: "good"},
#   {user_id: "5", restaurant_id: "24", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "26", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "5", restaurant_id: "28", rating: "5", content: ""},
#   {user_id: "5", restaurant_id: "30", rating: "4", content: ""},
#   {user_id: "5", restaurant_id: "31", rating: "2", content: "bad"},
#   {user_id: "5", restaurant_id: "32", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "33", rating: "5", content: ""},
#   {user_id: "5", restaurant_id: "34", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "5", restaurant_id: "35", rating: "2", content: ""},
#   # {user_id: "5", restaurant_id: "32", rating: "", content: ""},
#   # {user_id: "5", restaurant_id: "33", rating: "", content: ""},
#   # {user_id: "5", restaurant_id: "34", rating: "", content: ""},
#   # {user_id: "5", restaurant_id: "35", rating: "", content: ""},
#   {user_id: "5", restaurant_id: "36", rating: "4", content: ""},
#   {user_id: "5", restaurant_id: "37", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "5", restaurant_id: "38", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "39", rating: "4", content: "good"},
#   {user_id: "5", restaurant_id: "40", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "5", restaurant_id: "41", rating: "4", content: ""},
#   {user_id: "5", restaurant_id: "42", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "5", restaurant_id: "43", rating: "5", content: ""},
#   {user_id: "5", restaurant_id: "44", rating: "2", content: "bad"},
#   {user_id: "5", restaurant_id: "45", rating: "3", content: ""},
#   {user_id: "5", restaurant_id: "46", rating: "3", content: ""},
#
#
#   {user_id: "6", restaurant_id: "2", rating: "2", content: ""},
#   {user_id: "6", restaurant_id: "4", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "6", rating: "4", content: "good"},
#   {user_id: "6", restaurant_id: "8", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "10", rating: "2", content: ""},
#   {user_id: "6", restaurant_id: "12", rating: "4", content: ""},
#   # {user_id: "6", restaurant_id: "14", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "16", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "18", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "20", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "22", rating: "", content: ""},
#   {user_id: "6", restaurant_id: "24", rating: "3", content: ""},
#   {user_id: "6", restaurant_id: "26", rating: "5", content: ""},
#   {user_id: "6", restaurant_id: "28", rating: "2", content: "bad"},
#   {user_id: "6", restaurant_id: "30", rating: "4", content: "good"},
#   {user_id: "6", restaurant_id: "31", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "32", rating: "2", content: ""},
#   {user_id: "6", restaurant_id: "33", rating: "5", content: ""},
#   # {user_id: "6", restaurant_id: "34", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "35", rating: "", content: ""},
#   # {user_id: "6", restaurant_id: "32", rating: "", content: ""},
#   {user_id: "6", restaurant_id: "33", rating: "2", content: ""},
#   {user_id: "6", restaurant_id: "34", rating: "4", content: "good"},
#   {user_id: "6", restaurant_id: "35", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "36", rating: "4", content: "good"},
#   {user_id: "6", restaurant_id: "37", rating: "4", content: ""},
#   {user_id: "6", restaurant_id: "38", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "39", rating: "4", content: "good"},
#   {user_id: "6", restaurant_id: "40", rating: "3", content: ""},
#   {user_id: "6", restaurant_id: "41", rating: "3", content: ""},
#   {user_id: "6", restaurant_id: "42", rating: "2", content: "bad"},
#   {user_id: "6", restaurant_id: "43", rating: "5", content: ""},
#   {user_id: "6", restaurant_id: "44", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "6", restaurant_id: "45", rating: "4", content: ""},
#   {user_id: "6", restaurant_id: "46", rating: "3", content: ""},
#
#   {user_id: "7", restaurant_id: "2", rating: "4", content: "good"},
#   {user_id: "7", restaurant_id: "4", rating: "4", content: "good"},
#   {user_id: "7", restaurant_id: "6", rating: "5", content: "Thật tuyệt vời"},
#   # {user_id: "7", restaurant_id: "8", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "18", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "20", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "22", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "24", rating: "", content: ""},
#   {user_id: "7", restaurant_id: "26", rating: "2", content: ""},
#   {user_id: "7", restaurant_id: "28", rating: "4", content: "good"},
#   # {user_id: "7", restaurant_id: "30", rating: "", content: ""},
#   {user_id: "7", restaurant_id: "32", rating: "4", content: ""},
#   # {user_id: "9", restaurant_id: "43", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "44", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "45", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "46", rating: "", content: ""},
#   {user_id: "7", restaurant_id: "33", rating: "5", content: ""},
#   {user_id: "7", restaurant_id: "34", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "7", restaurant_id: "35", rating: "4", content: "good"},
#   {user_id: "7", restaurant_id: "32", rating: "2", content: "bad"},
#   {user_id: "7", restaurant_id: "33", rating: "4", content: ""},
#   {user_id: "7", restaurant_id: "34", rating: "3", content: ""},
#   {user_id: "7", restaurant_id: "35", rating: "4", content: "good"},
#   {user_id: "7", restaurant_id: "36", rating: "4", content: ""},
#   {user_id: "7", restaurant_id: "37", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "7", restaurant_id: "38", rating: "3", content: ""},
#   # {user_id: "7", restaurant_id: "39", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "40", rating: "", content: ""},
#   # {user_id: "7", restaurant_id: "41", rating: "", content: ""},
#   {user_id: "7", restaurant_id: "42", rating: "4", content: "good"},
#   {user_id: "7", restaurant_id: "43", rating: "2", content: "bad"},
#   {user_id: "7", restaurant_id: "44", rating: "5", content: ""},
#   {user_id: "7", restaurant_id: "45", rating: "2", content: ""},
#   {user_id: "7", restaurant_id: "46", rating: "3", content: ""},
#
#   {user_id: "8", restaurant_id: "2", rating: "4", content: ""},
#   {user_id: "8", restaurant_id: "4", rating: "4", content: "good"},
#   {user_id: "8", restaurant_id: "6", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "8", restaurant_id: "8", rating: "2", content: "bad"},
#   {user_id: "8", restaurant_id: "10", rating: "5", content: ""},
#   {user_id: "8", restaurant_id: "12", rating: "3", content: ""},
#   # {user_id: "8", restaurant_id: "14", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "16", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "18", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "20", rating: "", content: ""},
#   {user_id: "8", restaurant_id: "22", rating: "4", content: "good"},
#   {user_id: "8", restaurant_id: "24", rating: "3", content: ""},
#   {user_id: "8", restaurant_id: "26", rating: "4", content: ""},
#   {user_id: "8", restaurant_id: "28", rating: "2", content: "bad"},
#   {user_id: "8", restaurant_id: "30", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "8", restaurant_id: "31", rating: "4", content: "good"},
#   {user_id: "8", restaurant_id: "32", rating: "5", content: ""},
#   # {user_id: "8", restaurant_id: "33", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "34", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "35", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "32", rating: "", content: ""},
#   {user_id: "8", restaurant_id: "33", rating: "3", content: ""},
#   {user_id: "8", restaurant_id: "34", rating: "5", content: ""},
#   {user_id: "8", restaurant_id: "35", rating: "4", content: ""},
#   {user_id: "8", restaurant_id: "36", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "8", restaurant_id: "37", rating: "4", content: "good"},
#   {user_id: "8", restaurant_id: "38", rating: "3", content: ""},
#   {user_id: "8", restaurant_id: "39",rating: "2", content: "bad"},
#   {user_id: "8", restaurant_id: "40", rating: "5", content: ""},
#   {user_id: "8", restaurant_id: "41", rating: "4", content: ""},
#   {user_id: "8", restaurant_id: "42", rating: "5", content: ""},
#   {user_id: "8", restaurant_id: "43", rating: "3", content: ""},
#   # {user_id: "8", restaurant_id: "44", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "45", rating: "", content: ""},
#   # {user_id: "8", restaurant_id: "46", rating: "", content: ""},
#
#   # {user_id: "", restaurant_id: "2", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "4", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "6", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "8", rating: "", content: ""},
#   {user_id: "9", restaurant_id: "10", rating: "4", content: ""},
#   {user_id: "9", restaurant_id: "12", rating: "4", content: "good"},
#   {user_id: "9", restaurant_id: "14", rating: "2", content: "bad"},
#   {user_id: "9", restaurant_id: "16", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "9", restaurant_id: "18", rating: "4", content: "good"},
#   {user_id: "9", restaurant_id: "20", rating: "5", content: ""},
#   {user_id: "9", restaurant_id: "22", rating: "5", content: "Thật tuyệt vời"},
#   # {user_id: "9", restaurant_id: "24", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "26", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "28", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "30", rating: "", content: ""},
#   {user_id: "9", restaurant_id: "31", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "9", restaurant_id: "32", rating: "2", content: "bad"},
#   {user_id: "9", restaurant_id: "33", rating: "3", content: ""},
#   {user_id: "9", restaurant_id: "34", rating: "2", content: ""},
#   {user_id: "9", restaurant_id: "35", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "9", restaurant_id: "32", rating: "4", content: "good"},
#   {user_id: "9", restaurant_id: "33", rating: "2", content: "bad"},
#   {user_id: "9", restaurant_id: "34", rating: "5", content: ""},
#   {user_id: "9", restaurant_id: "35", rating: "4", content: ""},
#   {user_id: "9", restaurant_id: "36", rating: "4", content: ""},
#   {user_id: "9", restaurant_id: "37", rating: "5", content: "Thật tuyệt vời"},
#   {user_id: "9", restaurant_id: "38", rating: "5", content: ""},
#   {user_id: "9", restaurant_id: "39", rating: "4", content: "good"},
#   {user_id: "9", restaurant_id: "40", rating: "2", content: "bad"},
#   {user_id: "9", restaurant_id: "41", rating: "4", content: "good"},
#   # {user_id: "9", restaurant_id: "42", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "43", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "44", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "45", rating: "", content: ""},
#   # {user_id: "9", restaurant_id: "46", rating: "", content: ""},
#
#   ])
#
# Staff.create([
#   {restaurant_id: "2", kind: "Quản lý", name: "Phan Quân" , phone: "0905345365", salary: "10000000" , birthday: "1994-01-10", gender: "1"},
#   {restaurant_id: "2", kind: "Kế toán", name: "Phan Thị" , phone: "0989431653", salary: "5000000" , birthday: "1994-2-23", gender: "0"},
#   {restaurant_id: "2", kind: "Lễ tân", name: "Lê Trang" , phone: "09123164621", salary: "4500000" , birthday: "1994-3-24", gender: "0"},
#   {restaurant_id: "2", kind: "Đầu bếp", name: "Chu Tuấn" , phone: "01664774864", salary: "9000000" , birthday: "1993-6-2", gender: "1"},
#   {restaurant_id: "2", kind: "Bồi bàn", name: "Nguyễn Nhân" , phone: "0984156325", salary: "4000000" , birthday: "1994-12-25", gender: "1"},
#   {restaurant_id: "2", kind: "Bảo vệ", name: "Phan Hải" , phone: "0983431286", salary: "4000000" , birthday: "1994-6-15", gender: "1"},
#
#   {restaurant_id: "4", kind: "Quản lý", name: "Phan Quân" , phone: "0905345365", salary: "10000000" , birthday: "1994-01-10", gender: "1"},
#   {restaurant_id: "4", kind: "Kế toán", name: "Phan Thị" , phone: "0989431653", salary: "5000000" , birthday: "1994-2-23", gender: "0"},
#   {restaurant_id: "4", kind: "Lễ tân", name: "Lê Trang" , phone: "09123164621", salary: "4500000" , birthday: "1994-3-24", gender: "0"},
#   {restaurant_id: "4", kind: "Đầu bếp", name: "Chu Tuấn" , phone: "01664774864", salary: "9000000" , birthday: "1993-6-2", gender: "1"},
#   {restaurant_id: "4", kind: "Bồi bàn", name: "Nguyễn Nhân" , phone: "0984156325", salary: "4000000" , birthday: "1994-12-25", gender: "1"},
#   {restaurant_id: "4", kind: "Bảo vệ", name: "Phan Hải" , phone: "0983431286", salary: "4000000" , birthday: "1994-6-15", gender: "1"},
#
#   {restaurant_id: "6", kind: "Quản lý", name: "Phan Quân" , phone: "0905345365", salary: "10000000" , birthday: "1994-01-10", gender: "1"},
#   {restaurant_id: "6", kind: "Kế toán", name: "Phan Thị" , phone: "0989431653", salary: "5000000" , birthday: "1994-2-23", gender: "0"},
#   {restaurant_id: "6", kind: "Lễ tân", name: "Lê Trang" , phone: "09123164621", salary: "4500000" , birthday: "1994-3-24", gender: "0"},
#   {restaurant_id: "6", kind: "Đầu bếp", name: "Chu Tuấn" , phone: "01664774864", salary: "9000000" , birthday: "1993-6-2", gender: "1"},
#   {restaurant_id: "6", kind: "Bồi bàn", name: "Nguyễn Nhân" , phone: "0984156325", salary: "4000000" , birthday: "1994-12-25", gender: "1"},
#   {restaurant_id: "6", kind: "Bảo vệ", name: "Phan Hải" , phone: "0983431286", salary: "4000000" , birthday: "1994-6-15", gender: "1"},
#
#
#
#
#   ])
